### ISSUE TITLE
PhET-iO and sonification 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/tambo#1]
I would like to discuss possibilities for allowing our collaborators on the sonifcation project to use iO features to accomplish some sonification.

This strategy seems to have a couple of merits:
1. The researchers (I think) could have direct access to the data output of the sim and sonify that data externally, without us having to bake sonification into the sim. This approach would allow for rapid prototyping (and ideally relieve us of undo developer burden)
2. It would allow researchers to use 3rd party tools to create the sounds/soundscapes
3. Other people would be "shaking down" the API which seems beneficial
4. It shows off some more of the possibilities of the iO features

So...
- Does this approach seem feasible?
- Are there licensing issues? (I assume we would need to provide our "research" license)
- Roadblocks/problems?

**Comment by samreid** [comment]
@ariel-phet's next meeting with them is in 2 weeks.  Grant starts in October 1st.

@jbphet and @samreid could collaborate to put together a simple example.

@samreid recommends using PhET-iO Property.link instead of looking at the phetioEvent data stream.

**Comment by samreid** [comment]
Adding high priority since @ariel-phet would like to see something within a couple of weeks.

**Comment by pixelzoom** [comment]
The idea would be that researches would use this approach to iterate on sonification in a wrapper, then PhET would eventually pull the sonification back into the sim (since it ultimately needs to be available in non-PhET-iO versions.)

**Comment by samreid** [comment]
I'm going to take a look at this tonight.  Commits coming soon, if I make any progress.

**Comment by samreid** [comment]
Initial draft is working OK, the link is http://localhost/phet-io/html/wrappers/audio.html?sim=energy-skate-park-basics&screens=1&pitchProperty=energySkateParkBasics.introScreen.model.skater.skaterPositionProperty&pitchAccessor=y

**Comment by samreid** [comment]
@jbphet I'm at a good point to discuss this, please let me know when we can chat.

**Comment by samreid** [comment]
Published here: https://phet-io.colorado.edu/0.1/sims/energy-skate-park-basics/1.2.0-dev.1/phet-io/protected/wrappers/audio-local.html

I also updated the links in this version so it can be downloaded and run from file:// or localhost with no dependencies and no password required.

@ariel-phet can you take a look?  You probably already know this, but we want to focus on keeping the implementation simple, not on making beautiful music.

**Comment by ariel-phet** [comment]
@samreid certainly working...I know we don't want this to be beautiful, but for demo purposes it might be good to choose a slightly more pleasant sonic representation, more less the same thing you have done but perhaps a little less harsh :). Would be good to ask @jbphet to spend just a few minutes for something a bit more pleasant.

Can you give a "high level" description in this issue as to what was done to make this approach work.

And thanks for prototyping! Looks like a promising way to do things at first.

**Comment by samreid** [comment]
@jbphet can you take the lead on this, but let me know if I can assist?

**Comment by samreid** [comment]
> Can you give a "high level" description in this issue as to what was done to make this approach work.

I can do this part--I'll create issue #3 for it.

**Comment by samreid** [comment]
> Can you give a "high level" description in this issue as to what was done to make this approach work.

Each instrumented PhET-iO simulation has a number of variables that can be accessed from outside the simulation.  The list of available simulation variables can be obtained by running the "Instance-proxies" wrapper from http://localhost/phet-io/html/dev-wrappers.html.  Some of the variables are "Axon Property" values which means you can get their current value and receive a notification when the value has changed.  In the sample application, we have added a listener using the `link` function to the variable that indicates the skateboarder's position.  The variable is named `energySkateParkBasics.introScreen.model.skater.skaterPositionProperty`.  When the skater's position changes, the frequency of the noise changes accordingly.

@ariel-phet did you want any more detail for this?

**Comment by ariel-phet** [comment]
@samreid I think that is good for now, thanks!

**Comment by samreid** [comment]
@ariel-phet @jbphet prepared a new version which I posted here:
https://phet-io.colorado.edu/0.1/sims/energy-skate-park-basics/1.2.0-dev.2/phet-io/protected/apps/audio/audio.html?sim=energy-skate-park-basics

If it checks out, I'll want to do a few manual steps to make sure the file stands alone nicely before you deliver it to our collaborators.

**Comment by ariel-phet** [comment]
An improvement, and will do the job for now. Thanks @samreid

**Comment by samreid** [comment]
OK I've filled in relative paths so it should launch from anywhere (with the password).  Do not give out PhET's password, when they have signed a license agreement, let me know the name of their group or organization and I or Matt will create them a password:

https://phet-io.colorado.edu/0.1/sims/energy-skate-park-basics/1.2.0-dev.2/phet-io/protected/apps/audio/audio-local.html

**Comment by ariel-phet** [comment]
by an agreement, I assume you mean our CLA, or do you mean a PhET-iO agreement?

Just FYI, I already shared a demo (and PhET's password) with the IDRC folks today, did not seem like a big deal since they are collaborators and have signed an institutional CLA.

**Comment by samreid** [comment]
It probably did not do any harm to use PhET's password today, but I'd recommend for future usage creating separate accounts for each of our collaborators who need to access the protection PhET-iO materials.  Shall we create accounts for "idrc" and "georgia-tech"?

**Comment by ariel-phet** [comment]
@samreid sounds good

**Comment by ariel-phet** [comment]
Perhaps make a doc in the phet-io repo (or on unfuddle) to document?

**Comment by samreid** [comment]
This issue will help us create passwords for idrc and georgia-tech:
https://github.com/phetsims/phet-io/issues/601

> Perhaps make a doc in the phet-io repo (or on unfuddle) to document?

There is a "managing-passwords.md" on phet-io that describes how to create passwords for PhET-iO.  It is somewhat of a "faux-pas" to store passwords in plain text--if a group forgot their password we would probably just create them a new one.

**Comment by samreid** [comment]
OK I'll leave this assigned to @ariel-phet since the next step will be sharing to GT.

**Comment by samreid** [comment]
> It is somewhat of a "faux-pas" to store passwords in plain text--if a group forgot their password we would probably just create them a new one.

On the other hand, it would be a nice idea to keep a private list of the groups that have passwords.

**Comment by samreid** [comment]
In the private link mentioned above ⬆️  there is an issue for adding a list of groups that have phet-io passwords.

**Comment by ariel-phet** [comment]
Assigning over to @emily-phet now that she is back and the direct contact for the sonification work

**Comment by emily-phet** [comment]
@ariel-phet A few questions: 
I'm guessing the demo has not been shared with Georgia Tech, correct? 
Is there a timeline for when BAA can have this capability implemented? (I know that PhET-iO instrumentation of BAA is in progress, but wasn't sure of the timeline for that and any additional work

**Comment by ariel-phet** [comment]
@emily-phet 
- reminder to please assign me issues (especially now that github has multiple assignees, if not I might miss something)

- I believe the demo has been shared with Georgia Tech, not sure if they looked at it though
- timeline is a little up in the air. @jbphet is going to start getting up to speed on instrumentation, and begin chipping away. So ideally if the timeline for Georgia Tech work was a month or two out for actually needing the sim instrumented we would be in good shape. But if it becomes pressing, we can take a dedicated chunk of time in 2 or 3 weeks from now and get it done.
- TBD on a wrapper, but likely we would make some sort of more user friendly interface for experimenting with sonification through iO features. To begin with directly through the API makes the most sense until we see what is most relevant

**Comment by emily-phet** [comment]
Timeline has been determined - first two screens of BAA already instrumented with PhET-iO as needed by Sonification Lab). Plans for instrumentation of other sims Sonification Lab will work with are in place. Licensing relationship is also under way.
