### ISSUE TITLE
incorrect singleton pattern for pushButtonSoundPlayer

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#104]
Noted while working on https://github.com/phetsims/chipper/issues/932.

In pushButtonSoundPlayer.js:

```js
class pushButtonSoundPlayer {
...
  /**
   * @public
   * @returns {pushButtonSoundPlayer}
   */
  static getInstance() {
    if ( instance === null ) {
      instance = new pushButtonSoundPlayer();
    }
    return instance;
  }
...
} 

tambo.register( 'pushButtonSoundPlayer', pushButtonSoundPlayer );
export default pushButtonSoundPlayer;
```

I'm guessing that the intent was to create a singleton that is instantiated on demand. But a class should not have a lowercase class name.   And `pushButtonSoundPlayer.getInstance()` doesn't look at all like a static method call.

Rename `pushButtonSoundPlayer` to `PushButtonSoundPlayer`. Export `getInstance` only.  Then call like this:

```js
const pushButtonSoundPlayer = PushButtonSoundPlayer.getInstance();
```

**Comment by jbphet** [comment]
Oops, this was an early experiment from the effort to create shared sound players for common UI components that I neglected to delete.  It's gone now.  The actual singleton for this can be found at https://github.com/phetsims/tambo/blob/master/js/shared-sound-players/pushButtonSoundPlayer.js as of this writing.

Thanks for bringing this to my attention.  Closing.
