### ISSUE TITLE
JT Humming doesn't happen right away after unmuting

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#105]
**Test device**
Dell or iPad
**Operating System**
Win 10 or IPadOS 13
**Browser**
Chrome or Safari
**Problem description**
For https://github.com/phetsims/vibe/issues/33. Unsure if general or JT specific, so putting here. Move if JT specific. Does not occur in published.
 If you mute John Travoltage, add electrons, and then unmute, the humming sound that should be there does not occur. You need to do something like cause a discharge to get it started.
**Steps to reproduce**
1. Go to JT and use nav bar to mute sim before anything else.
2. Move hand away from knob
3. Add large number of charges.
4. Unmute
5. Add more charges and listen.
6. Discharge slightly and listen

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: John Travoltage
URL: http://phettest.colorado.edu/john-travoltage/john-travoltage_en.html?ea&brand=phet
Version: 1.6.0-dev.17 (require.js)
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36
Language: en-US
Window: 1536x722
Pixel Ratio: 2.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by jbphet** [comment]
I believe this problem was introduced in https://github.com/phetsims/tambo/commit/49ae465a39dfb75a2112123d39c9cd32c444f73b.  The commit message for that commit is incorrect, and I'm wondering if it was accidentally committed while doing some other experimentation.  It should be fixed now.  @KatieWoe - can you please test this on master?

**Comment by KatieWoe** [comment]
looks good on master
