### ISSUE TITLE
SoundClip to swap out WrappedAudioBuffers?

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#108]
While working on #9, I found myself recreating a lot of SoundClip instances to support designing options (via the options dialog). This isn't production code, but it does seem to be a quite common usage of SoundClip. What I would love to be able to do is:

```js

const mySoundClip = new SoundClip( choice1 );

choiceSelectionProperty.link( choice=> {
  if( choice === 0 ){
    mySoundClip.setSound( choice1 );
  }
  if( choice === 1 ){
    mySoundClip.setSound( choice2 );
  }
  if( choice === 2 ){
    mySoundClip.setSound( choice3 );
  }
} );
```

Does this seem reasonable? Would it be valuable to you? Is it even possible?

**Comment by jbphet** [comment]
Wouldn't `MultiClip` work well for this?  Just create a map of sound-to-values and load 'er up.  Take a look at that, then let me know if you're looking for something more specific to this particular problem.

**Comment by zepumph** [comment]
That is a great idea. Thanks for showing that to me!
