### ISSUE TITLE
Add SoundClipChord to Tambo

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#110]
from https://github.com/phetsims/ratio-and-proportion/issues/9#issuecomment-637804363, it was recommended that instead of removing this SoundGenerator, because it is no longer needed in Ratio and Proportion, to instead move it to tambo. I will also add a sample for it.

**Comment by zepumph** [comment]
@jbphet anything else here?

**Comment by jbphet** [comment]
Looks good to me.  Thanks for doing this - it's very cool, and I hope it makes it into a sim soon.  Closing.
