### ISSUE TITLE
InvertedBooleanProperty should not be settable, or should have 2-way binding

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#111]
During https://github.com/phetsims/wave-interference/issues/426 it was recommended to use InvertedBooleanProperty.  I discovered there is a problem that you can set its value independently.

```js
const x = new BooleanProperty(false);
const y = new InvertedBooleanProperty(x);
y.value = false;
```

Have you considered implementing InvertedBooleanProperty using DynamicProperty, which supports one-way or two-way binding?

Have you considered implementing InvertedBooleanProperty as a DerivedProperty, like:

```js
new DerivedProperty( [ xProperty ], x => !x )
```

**Comment by jbphet** [comment]
> Have you considered implementing InvertedBooleanProperty using DynamicProperty...?
> Have you considered implementing InvertedBooleanProperty as a DerivedProperty...?

I hadn't thought about it much at all, I just wanted it and whipped it up quickly.  It's a good point that it can be set independently, which is undesirable.  I've revised it to use the DerivedProperty approach described above, and this makes it very compact.

Good suggestion @samreid.  Good to go?  Do we need to think about passing in a tandem or options?

**Comment by samreid** [comment]
I recommend passing through `options` so usage sites can pass options as necessary.

**Comment by jbphet** [comment]
Options added.  Are we done here?

**Comment by samreid** [comment]
The options look great, I just added one improvement to the JSDoc. The last thing is it seems this belongs in axon--nothing about it seems tambo specific (except that tambo may use it).  

Finally, I noticed the definitions of `DerivedProperty.and` and `DerivedProperty.or` and was wondering if this should be defined as `DerivedProperty.not` to fit in better.

**Comment by jbphet** [comment]
> I noticed the definitions of `DerivedProperty.and` and `DerivedProperty.or` and was wondering if this should be defined as `DerivedProperty.not` to fit in better.

That seems great, I didn't realize it was an option.  I went with it, please review and close if you're good with it.

**Comment by samreid** [comment]
Looks great, thanks!  Closing.
