### ISSUE TITLE
Consider reducing volume of reset

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#112]
I've gotten feedback from a couple of PhET team members lately that the reset sound is a bit loud, especially considering that it is a UI sound, which we've made an effort to make fairly innocuous.  This is based on how people have their volume set during normal usage.  This is a bit tricky, because the reset is what we've used as the reference for our previous mixes, but I still think we can take it down a bit without too much disruption.  In other words, I don't think we'll need to re-mix the existing sonified sims.

@Ashton-Morris and @emily-phet - Let's have a listen at our next sound design meeting and see if we feel that an adjustment should be made.

**Comment by emily-phet** [comment]
@jbphet Just a note from last Tuesday's meeting - we decided that lowering the reset all sound would be just fine. We thought maybe on the order 20% of perceived volume.

**Comment by jbphet** [comment]
I did a bit of research to see if I could come up with a rigorous way to reduce the perceived volume by 20%.  This turns out to be a bit tricky, so I used the information that I found in [this PDF file about human perception of sound](https://modularwalls.com.au/wp-content/uploads/Human-perception-of-sound_April2016-WEB.pdf), specifically this bit:

![image](https://user-images.githubusercontent.com/3082831/84698431-0a45be80-af0d-11ea-88a5-c5e35fb5b152.png)

I then recorded the output level of the current `resetAllSoundPlayer` using some free recording software and then measured the level using the "Measure RMS" analyzer in Audacity.  The output level setting in `resetAllSoundPlayer` was at 0.7 at the start of this endeavor, and the measurement yielded an RMS value of -17.6 dB RMS.  Through trial and error, I was able to reduce the output level to -22.9 dB RMS by using an output level setting of 0.39, which is reasonably close to a -5 dB change.  This sounded pretty good to me, so I'll commit it and we can check it out at the next sound design meeting.

**Comment by jbphet** [comment]
@emily-phet and @Ashton-Morris - Please compare the reset volume level in these two different versions of the tambo demo and let me know if you think this is the right amount of reduction.  I thought it might actually be a bit too much, so I'm interested in your input.

- Before reduction: https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.13/phet/tambo_en_phet.html
- After reduction: https://phet-dev.colorado.edu/html/tambo/1.0.0-dev.14/phet/tambo_en_phet.html

**Comment by Ashton-Morris** [comment]
@jbphet I think the volume changes are good. Specifically when I click through the bottom screen changes and then hit the reset, they all seem to have a good continuity.

**Comment by jbphet** [comment]
I'm going to call things good based on @Ashton-Morris's feedback and my own opinion and close this.
