### ISSUE TITLE
Remove stubbed audio context

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#113]
PhET is discontinuing support for Internet Explorer as documented in https://github.com/phetsims/tasks/issues/1037.  `phetAudioContext` currently creates a stubbed version of a Web Audio audio context when running on IE so that things don't crash.  It may be possible now to remove this, which would simplify the code.

It will be important to test on all supported platforms once this change is made in order to make sure it doesn't cause any problems.

Also, the query parameter `forceStubbedAudioContext` should be removed from `initialize-globals` when this work is done.

**Comment by jbphet** [comment]
This is done.  Assigning to @KatieWoe for two reasons:

1. Heads up - IE will not longer work at all.  We're adding a message about this, see https://github.com/phetsims/tasks/issues/1037, but based on my testing this is the first thing that will actually cause loading of IE to fail.
2. We should regression test sound on multiple platforms.  I did my own tests on Chrome, Firefox, Edge, Safari, and Mobile Safari, but I suggest that QA test the master versions of several sound-generating sims on all our major platforms just to double check.

**Comment by jbphet** [comment]
@KatieWoe requested (via Slack) that I publish dev versions for testing this as we did for https://github.com/phetsims/vibe/issues/33.  Here they are:

- https://phet-dev.colorado.edu/html/molarity/1.6.0-dev.4/phet/molarity_en_phet.html
- https://phet-dev.colorado.edu/html/john-travoltage/1.6.0-dev.21/phet/john-travoltage_en_phet.html
- https://phet-dev.colorado.edu/html/plinko-probability/1.2.0-dev.6/phet/plinko-probability_en_phet.html
-  https://phet-dev.colorado.edu/html/forces-and-motion-basics/2.4.0-dev.5/phet/forces-and-motion-basics_en_phet.html

**Comment by KatieWoe** [comment]
Using this comment to record platforms:
Windows done

**Comment by KatieWoe** [comment]
From Slack:
>Kathryn Woessner  3:08 PM
Is (this issue) still relevant?
John Blanco  3:10 PM
Probably not.  I think we'd know by now if there were sound issues on any other platforms.  Feel free to note that I said this and close it.
