### ISSUE TITLE
"SoundGenerator" vs "SoundPlayer"

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#116]
This minor terminology issue is a bit confusing while poking around the tambo. I think that "sound player" is vestigial, but we still have `Playable`, and we also have many `*SoundPlayer.js` types in `tambo/js/shared-sound-players`.

Over to @jbphet to discuss.

**Comment by jbphet** [comment]
A sound player is a sound generator that implements the `Playable` interface, meaning that it is meant produce sound by invoking the `play` method.  All sound players and sound generators, but not all sound generators are sound players.  An example of a sound generator that is *not* a sound player is one that takes a property and plays sound based on the state and/or transitions for that property.

I've added this term to the User Guide document.

@zepumph - please let me know if this is clear and useful, and whether you feel like any more information is needed on the subject.

**Comment by zepumph** [comment]
Makes sense to me! Thanks.
