### ISSUE TITLE
Move MultiSoundClip to common code

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#123]
I used a new type in ratio and proportion to play two sounds together at the same time. It is a sound type, and it seems to be sticking around for that sim, so I might as well move it to common code and add a demo for it.

**Comment by zepumph** [comment]
I came to this issue from https://github.com/phetsims/ratio-and-proportion/issues/127 and a TODO in `MovingInProportionSoundGenerator`.

**Comment by zepumph** [comment]
@jbphet, this is pretty much a light wrapper for SoundClip, and not too complicated. This is ready for review. What do you think?

**Comment by jbphet** [comment]
It mostly looks good to me, and thanks for also adding it to the test harness.  I'm a little concerned that it will be easy to confuse `MultiClip` and `MultiSoundClip` given the similarity of the names.  How about `CompositeSoundClip`?

**Comment by zepumph** [comment]
No preference here, whatever you would like.

**Comment by jbphet** [comment]
I went ahead with changing `MultiSoundClip` to `CompositeSoundClip` to avoid confusion with `MultiClip`.  @zepumph - assigning to you to make sure that you see this, since it touches ratio-and-proportion.  After that it can be closed, at least as far as I am concerned.
