### ISSUE TITLE
review changes to AmplitudeModulator

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#125]
In https://github.com/phetsims/tambo/commit/4f7f458304cff39d64d02574d69b0d5fbaa58535 for https://github.com/phetsims/sun/issues/585, AmplitudeModulator was converted to use EnabledComponent mixin.   @jbphet referred me to the tambo demo to test, but I see nothing in that demo that allows me to test enabledProperty.

I also noticed that there was no implementation of `dispose`, and that this class leaks if any of the optional Properties are provided.  So I fixed that.  Common code should implement dispose or document why it does not.

@jbphet please review.

**Comment by jbphet** [comment]
Changes look good to me, and it is behaving correctly in the test harness.  Thanks @pixelzoom.  Closing.
