### ISSUE TITLE
How should disable of sound generation during reset work?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#13]
As of this writing, the sonification manager (soon to be renamed sound manager) has no awareness of which screens are associated with which sounds.  One of the early incarnations *did* have this awareness so that continuous sounds associated with a particular screen could be muted when that screen was not visible, but that was replaced by associating a sound with a Scenery node and disabling that sound when the node was not displayed in the scene graph.

The problem with this is that reset happens per screen, so if a sound needs to be muted during a reset, it should be disabled only when the reset occurs for the screen it is on.  At the moment, this isn't how it works.  Instead, the sonification manager amalgamates all the reset events for the screens into a single property that basically says, "a reset is occurring somewhere in the simulation" and passes it to all sound generators.  This is awkward, and we should do it differently.

Several ideas were kicked around during the 6/14/2018 design meeting, and we decided to create this issue and track them, and then make a decision on the best approach.

**Comment by jbphet** [comment]
@samreid suggested just passing in an enable control property that corresponds to the reset when the sound generator is registered, so that the sound generator doesn't need to be aware of resets at all.  This would work pretty well for most things, but will require passing the reset emitter or "resetNotInProgress" property down to any composite components that are created, which could be a bit of a hassle.

**Comment by jbphet** [comment]
@zepumph suggested having separate instances of the sonification manager, one per screen (similar to how `ScreenView` works for the visual presentation), and each of those would have its own resetInProgress property.  This could work, but we'd still need a single root instance where global control occurred (e.g. sound enabled, basic/enhanced, etc).

**Comment by jbphet** [comment]
@ariel-phet suggested that I mark this for the next dev meeting and we discuss it further there.

**Comment by samreid** [comment]
> if a sound needs to be muted during a reset, it should be disabled only when the reset occurs for the screen it is on. 

I'm confused--it is already muted if it is on another screen, so how is this a problem?  That is, how does it cause a problem to mute sounds from non-selected screens?  I'm guessing I'm just misunderstanding something about the problem.

**Comment by samreid** [comment]
> that it would be good to have an instance per screen of the sound manager and track the resets for each screen.

So we will need to pass the soundManagerScreenInstance into each ScreenView and recursively to its components?  Also @jbphet I'm still confused about the nature of the problem, can you please respond to https://github.com/phetsims/tambo/issues/13#issuecomment-398975266 at your convenience?

**Comment by jbphet** [comment]
> So we will need to pass the soundManagerScreenInstance into each ScreenView and recursively to its components?

I don't think we will need to pass it into the ScreenView so much as create it there, at least that's what I'm thinking at this point.  And yes, if sub-components need to add sounds, it would need to be passed to that sub-component.

> I'm confused--it is already muted if it is on another screen, so how is this a problem?

It's not a problem in the sense that any incorrect behavior would occur, it's just a bit architecturally ugly because notifications of reset on one screen will be going to components that are not on that screen.  As things are currently envisioned, this wouldn't cause any side effects, but if, say, reset was ever made into a special case, this would cause problems.

**Comment by samreid** [comment]
I thought we had discussed something like passing a `resetEmitter` into screen sub-components.  See https://github.com/phetsims/tambo/issues/13#issuecomment-397445496  How is passing a `soundManagerScreenInstance` to screen sub-components a superior alternative?

**Comment by jbphet** [comment]
@samreid - unfortunately you were unavailable for the last sonification meeting where this was discussed.  I'll put it on the agenda to re-discuss this Thursday before I begin implementation.

**Comment by jbphet** [comment]
The muting during reset has been implemented as agreed to above, closing.

**Comment by samreid** [comment]
We discussed this problem again on Thursday and agreed to try a new pattern where the sound is wired up to the UI component, rather than watching the model only.  This means it will not need to know about the `resetInProgressProperty` at all.  The pseudocode would be something like:

```js
// on user interface component fired
modelProperty.change();
userInterfaceSonificationEmitter.emit();
```

Tagging @jbphet in case he has more notes or another issue to refer to, feel free to close this issue as well if it is no longer useful.

**Comment by jbphet** [comment]
> We...agreed to try a new pattern where the sound is wired up to the UI component, rather than watching the model only.

This pattern is working well in the work I've been doing recently for common UI sounds (see https://github.com/phetsims/tambo/issues/73), and I plan to try to continue in this direction from here on.  I'm closing this issue, and will re-open if it needs more work.
