### ISSUE TITLE
remove dependency on joist in soundManager

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#131]
This would involve refactoring DisplayedProperty to add a listener to ALL displays, instead of just the display passed in. This is a new feature created in https://github.com/phetsims/scenery/issues/1149. @jbphet would you like to take it for a test drive here?

Generally related to https://github.com/phetsims/tambo/issues/126

**Comment by jbphet** [comment]
I'm seeing three joist dependencies in the current version of `soundManager`.  They are:

- window.phet.joist.sim.isConstructionCompleteProperty
- phet.joist.sim.isSettingPhetioStateProperty
- phet.joist.display

@zepumph - by "take it for a test drive here", are you requesting that I eliminate all of these dependencies, eliminate just the display dependency, or something else?  I'm happy to do it, I just want to make sure that we're clear on the goal, since it seems like the title and the description weren't quite in sync.  Oh, and I edited the title a little too.

**Comment by zepumph** [comment]
Yes I think that ideally soundManager should work just as well if the `joist` global exists or not. Thus I recommend the following two tasks:

* Update how DisplayedProperty works such that it adds a a static listener, like `Display.addInputListener` (to all displays)
* Gracefully support calling the soundManager enabled even if the joist Properties don't exist. It should be easy since initialize options is already set up. What do you think about something like:
```diff
Index: joist/js/Sim.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/joist/js/Sim.js b/joist/js/Sim.js
--- a/joist/js/Sim.js	(revision dfcb8cf5ae3127dc67a56c36f0e1e421ab428825)
+++ b/joist/js/Sim.js	(date 1612220956898)
@@ -492,7 +492,14 @@
 
     // Initialize the sound library if enabled, then hook up sound generation for screen changes.
     if ( this.supportsSound ) {
-      soundManager.initialize( this.browserTabVisibleProperty, this.activeProperty );
+      soundManager.initialize( {
+        fullEnabledDependencyProperties: [
+          this.browserTabVisibleProperty,
+          this.activeProperty,
+          this.isConstructionCompleteProperty,
+          this.isSettingPhetioStateProperty
+        ]
+      } );
       soundManager.addSoundGenerator(
         new ScreenSelectionSoundGenerator( this.screenProperty, this.homeScreen, { initialOutputLevel: 0.5 } )
       );
Index: tambo/js/soundManager.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/tambo/js/soundManager.js b/tambo/js/soundManager.js
--- a/tambo/js/soundManager.js	(revision 28abc68a5323fa9aca2c486e512b5fd9bdf7b81f)
+++ b/tambo/js/soundManager.js	(date 1612220983996)
@@ -92,12 +92,10 @@
 
   /**
    * Initialize the sonification manager. This function must be invoked before any sound generators can be added.
-   * @param {BooleanProperty} simVisibleProperty
-   * @param {BooleanProperty} simActiveProperty
    * @param {Object} [options]
    * @public
    */
-  initialize( simVisibleProperty, simActiveProperty, options ) {
+  initialize( options ) {
 
     assert && assert( !this.initialized, 'can\'t initialize the sound manager more than once' );
 
@@ -106,8 +104,10 @@
       // Categories that can be used to group sound generators together and control their volume as a group - the
       // names can be anything that will work as a key for a JavaScript object, but initially we've chosen to use
       // names with conventions similar to what is commonly seen for CSS classes.
-      categories: [ 'sim-specific', 'user-interface' ]
+      categories: [ 'sim-specific', 'user-interface' ],
 
+      // {Property.<boolean>[]}
+      fullEnabledDependencyProperties: []
     }, options );
 
     // validate the options
@@ -168,16 +168,11 @@
     // hook up a listener that turns down the gain if sonification is disabled or if the sim isn't visible or isn't
     // active
     Property.multilink(
-      [
-        this.enabledProperty,
-        window.phet.joist.sim.isConstructionCompleteProperty,
-        simVisibleProperty,
-        simActiveProperty,
-        phet.joist.sim.isSettingPhetioStateProperty
-      ],
-      ( enabled, simInitComplete, simVisible, simActive, simIsSettingPhetioState ) => {
+      [ this.enabledProperty ].concat( options.fullEnabledDependencyProperties ),
+      ( enabled, ...fullyEnabledDependencies ) => {
+        fullyEnabledDependencies = fullyEnabledDependencies || [ true ];
 
-        const fullyEnabled = enabled && simInitComplete && simVisible && simActive && !simIsSettingPhetioState;
+        const fullyEnabled = enabled && _.every( fullyEnabledDependencies );
         const gain = fullyEnabled ? this._masterOutputLevel : 0;
 
         // set the gain, but somewhat gradually in order to avoid rapid transients, which sound like clicks
```


What do you think?

**Comment by jbphet** [comment]
@jonathanolson - I'm working to eliminate dependencies on joist for this repo (tambo), and the last one is a dependency on the global display variable.  The code the dependency looks like this:

```
    // If a view node was specified, create and pass in a boolean Property that is true only when the node is displayed.
    if ( options.associatedViewNode ) {
      soundGenerator.addEnableControlProperty(
        new DisplayedProperty( options.associatedViewNode, phet.joist.display )
      );
    }
```

I'm not sure how best to do this.  Could `DisplayedProperty` be modified to use *any* display instead of having to specify one?  Could there be a way to get the available displays from Scenery?  Do you have any other ideas that would work?

**Comment by zepumph** [comment]
Yes you can add a listener to all displays with `Display.addInputListener`, see first bullet in https://github.com/phetsims/tambo/issues/131#issuecomment-771225456.  (added in https://github.com/phetsims/scenery/commit/b64bf00bf1771853f58401a0f973f05ff46da798 for https://github.com/phetsims/scenery/issues/1149). I think it was added exactly for this case. How fun!

**Comment by jbphet** [comment]
@zepumph and I just talked over Slack & Zoom, and it sounds like creating what `soundManager` needs in this regard, which is a property that is true when a node is displayed and false otherwise, isn't as easy as he may have initially thought using `Display.addInputListener`.  He said he would take this on for now and will talk with @jonathanolson about it.

**Comment by zepumph** [comment]
Alright, DisplayedProperty now supports any display. With the help of @jonathanolson, this was a very simple change, pretty much just this logic update:

https://github.com/phetsims/scenery/blob/363f3b699fe7c9c7379f959e6aefcf1723597269/js/nodes/Node.js#L6099

To allow an optional display param to be null when all displays should be respected.
Note https://github.com/phetsims/scenery/issues/1167 as the next step for makind DisplayedProperty more robust (supporting visually hidden Nodes that are still visible in the PDOM, and thus still displayed somewhere).

@jbphet this removes the final joist dependency. What else is left for this issue?

**Comment by jbphet** [comment]
I removed one more usage of a joist global that should be redundant since is was the property that tracks phet-io state setting, and that property is now used in `soundManager` to disable sound production.  I think we're done here.  Closing.
