### ISSUE TITLE
branch: preferences

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tambo#138]
The preferences dialog has an "All Audio" toggle that enables/disabled all audio in the simulation, including sound, enhanced sound and voicing. This requires another Property to control audio output in soundManager. The change is relatively simple but it is in a branch for a while while we have Preferences in a joist branch for a little longer in https://github.com/phetsims/joist/issues/694.

**Comment by zepumph** [comment]
Any updates here @jessegreenberg? Do we still need this branch?

**Comment by jessegreenberg** [comment]
Nope, thanks, branch deleted.
