### ISSUE TITLE
SharedSoundClip stop is needed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#139]
I have a need in Fourier to `stop` a shared sound clip.  

@jbphet is it OK to add a `stop` method to SharedSoundClip?

**Comment by pixelzoom** [comment]
I created this issue in the wrong repo.  Transferred from tandem to tambo.

**Comment by pixelzoom** [comment]
Discussed with @jbphet via Zoom.   SharedSoundClip is being renamed to SoundClipPlayer in https://github.com/phetsims/tambo/issues/142.   Playable should implement `stop` in addition to `play`.

**Comment by jbphet** [comment]
Looks good to me.  I've also modified `Playable.js`.  Closing.
