### ISSUE TITLE
"SoundPlayer" naming of SharedSoundClip instances is confusing and violates PhET naming conventions.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#142]
tambo/js/shared-sound-players/ contains a collection of shared sounds, all with file names of the form `{{somethingDescriptive}}SoundPlayer.js`

PhET naming convention has been to use names that reflect the class.  That has not been done here, and I think it's confusing.  For example:

```
const accordionBoxClosedSoundPlayer = new SharedSoundClip( accordionBoxClosedSound, {
```

So when I see it in context, like

`accordionBoxClosedSoundPlayer.play()`, I cannot identify it as a SharedSoundClip.  There is also nothing in the class hierarchy or composition of SharedSoundClip that is a "sound player", so I'm can't identify what this naming is referring to.

Why is this not named `accordionBoxClosedSharedSoundClip`?

**Comment by pixelzoom** [comment]
I created this issue in the wrong repo.  Transferred from tandem to tambo.

**Comment by pixelzoom** [comment]
Discussed with @jbphet via Zoom, consensus:

* SoundClipPlayer is a better name for SharedSoundClip, since it implements the Playable interface, and while not a SoundClip, it plays a SoundClip.
* Playable should also implement `stop`

**Comment by jbphet** [comment]
@pixelzoom and I had a discussion today about what should be available through the `SoundClipPlayer` API, and decided that only the `play` and `stop` methods should be supported, and I'll add a method to get the actual clip that could be used for additional control, but I'll include a lot of warning info in the documentation.

**Comment by jbphet** [comment]
@pixelzoom - The name has been changed and the API modified a bit to support retrieval of the sound clip for cases where additional information is needed.  I'm good to close this if you are.

**Comment by pixelzoom** [comment]
Looks good.  Since accordionBoxClosedSoundPlayer.js et. al. actually return an instance of SoundClipPlayer, and there is no SoundPlayer type.  So should they be renamed to (e.g.) accordionBoxClosedSoundClipPlayer.js ?  I realize that's a pain and a bit verbose, but it's more aligned with PhET naming conventions.

**Comment by pixelzoom** [comment]
Same question for options whose value is of type `{SoundClipPlayer}`, for example in AccordionBox.js:

```js
      // {Playable} - sound generators for expand and collapse
      expandedSoundPlayer: accordionBoxOpenedSoundPlayer,
      collapsedSoundPlayer: accordionBoxClosedSoundPlayer,
```

**Comment by jbphet** [comment]
I'm not too hip on the idea of adding "SoundClipPlayer" to the end of all of these things for two reasons.  One is that it's awfully verbose.  Another is that the items don't have to be of the type `SoundClipPlayer`, they just have to adhere to the `Playable` interface (like an interface definition in Java).

Here's a proposal: What if we change the name of the `Playable` definition type to be `SoundPlayer`.  It's a bit less ambiguous (`Playable` could refer to a game),  and then we could keep the names like `expandedSoundPlayer`, which strike me as pretty readable.

**Comment by pixelzoom** [comment]
Your proposal sounds great.

**Comment by jbphet** [comment]
Change made.  @pixelzoom - please have a look and, if you're good with it, I think this issue can be closed.

**Comment by pixelzoom** [comment]
Looks good to me. But you somehow lost the commit history for Playable.js when you renamed it to SoundPlayer.js.   There's now only 1 commit:

```js
% cd tambo
% git log SoundPlayer.js 
commit ef1f782e79e28eac4d6490b8065af523efc35c5b (HEAD -> master, origin/master, origin/HEAD)
Author: jbphet <john.blanco@colorado.edu>
Date:   Tue Jul 27 11:05:07 2021 -0600

    changed Playable to SoundPlayer, see https://github.com/phetsims/tambo/issues/142
```

Back to @jbphet to decide whether history needs to be restored. Personally, I wouldn't bother, but I don't know how much history there was.

**Comment by jbphet** [comment]
Yeah, I don't think I'll take the time to restore the history.  There wasn't a lot of it, and the file is pretty straightforward.  I'm not sure why that happened though, and I'll keep an eye out for whether there is something that I did that caused it.

Closing.
