### ISSUE TITLE
Should there be an option to automatically add a sound generator to the sound manager?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#144]
As of this writing, sound generators have to be created and then added to the sound manager.  Sound generators aren't automatically added because sometimes we want to interconnect them in more complicated patterns, and because creating something and adding it to something else is a common pattern in our graphical interface development, so it seemed like a reasonable parallel.

However, after working with this for a while, it seem like it would be nice if a sound generator could automatically be added to the sound manager, since probably 90% of the time that's what the next line of code does.

I'm going to mark this for developer meeting to get input from other devs.

**Comment by samreid** [comment]
It would be nice to have the default be to add to the sound manager, with an option to opt-out.  Hopefully this will not create a module import cycle.  Maybe the option would default to `soundManager: soundManager` and if you want to opt out you would put `soundManager: null`?  Can one sound be added to multiple sound managers?

**Comment by jbphet** [comment]
We discussed this in today's developer meeting and decided that having the explicit add step is preferred.  It makes it more obvious what's going on, is similar to the way Scenery works (which all developers know), and there are options to the `addSoundGenerator` call that would have to be passed in.  So, the bottom line is to leave it as is, at least for now.  Closing.
