### ISSUE TITLE
Was the soundManager.enabledProperty default value change intentional?

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#146]
CT pointed out this error for several repos:

```
natural-selection : phet-io-api-compatibility : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1626740361976/natural-selection/natural-selection_en.html?continuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-api-compatibility%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1626740361976%22%2C%22timestamp%22%3A1626742310099%7D&ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Query: ea&brand=phet-io&phetioStandalone&phetioCompareAPI&randomSeed=332211
Uncaught Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:

naturalSelection.general.view.soundManager.enabledProperty._data.initialState differs.
Expected:
{"units":null,"validValues":null,"value":true}
actual:
{"value":false,"validValues":null,"units":null}

Error: Assertion failed: Designed API changes detected, please roll them back or revise the reference API:
```

It appears the `soundManager.enabledProperty` changed from true to false for several sims.  Perhaps this issue is related to other sound work today, such as https://github.com/phetsims/joist/issues/734 or maybe https://github.com/phetsims/chipper/issues/1031

**Comment by samreid** [comment]
Since I haven't heard of sims like natural selection supporting audio, I will infer that this is an intentional change, and I'll update the PhET-iO API files by running: `grunt generate-phet-io-api --simList=../perennial/data/phet-io-api-stable`

**Comment by samreid** [comment]
I committed the API change in the commit, not entirely confident that it is the desired direction.  Feel free to roll it back if the change was unintentional.  Assigning @zepumph @jbphet and @jessegreenberg since they worked in the related issues mentioned above.

**Comment by jessegreenberg** [comment]
Thanks @samreid - I made this change in https://github.com/phetsims/tambo/commit/548817f25388b1f97bbdfdabdbf98f2519c27341 for https://github.com/phetsims/joist/issues/734 and didn't consider the PhET-iO implication. But I think this is correct and is assigned for review as part of https://github.com/phetsims/joist/issues/734. But will leave this open to verify by @jbphet.

Specifically, description for why this was changed is described in https://github.com/phetsims/joist/issues/734#issuecomment-882750179.

**Comment by jbphet** [comment]
The change makes sense to me.  Closing.
