### ISSUE TITLE
Delete FourierToneGenerator?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#148]
@jbphet wondering if tambo/FourierToneGenerator.js should be deleted, since it's not actually being used in Fourier.  I've accidentally navigated to it more than once.

**Comment by jbphet** [comment]
Sure, I can get rid of it.

In case we ever need it, here's a little historical context: `tambo/FourierToneGenerator.js` was created as a sort of reference design to help @pixelzoom get started on the process of adding sound generation for the harmonics used in the fourier-making-waves sim.  As of this writing, the sound generator that was ultimately created for this by @pixelzoom is `fourier-making-waves/FourierSoundGenerator.js`.

Closing.
