### ISSUE TITLE
Sound heard with 'audio=disabled'

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/tambo#155]
When testing https://github.com/phetsims/balloons-and-static-electricity/issues/543 with MacBook Air (m1 chip) iOS 11.6 + Safari 15, the first item I interacted with produced a sound and then all subsequent sounds were muted. 

Please turn your volume up in order to hear:
https://user-images.githubusercontent.com/87318828/137906239-e780f3fb-af1b-47a9-a8c0-b9d9eed60368.mov

**Comment by jbphet** [comment]
@Nancy-Salpepi - This issue has been around for a couple of years and it hasn't been addressed, mostly because it hasn't risen to the top of my priorities.  Can you test again and see if it is still a problem?  Sometimes these things go away with new releases of the browers.

**Comment by Nancy-Salpepi** [comment]
@jbphet I tried several sims with ?audio=disabled and  I can no longer reproduced this issue with macOS 14.1.2 and safari 17.1.2 (or chrome). 
Closing!
