### ISSUE TITLE
Rename "Enhanced Sounds" to "Extra Sounds"

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#165]
Over in https://github.com/phetsims/joist/issues/744 and https://github.com/phetsims/phet-io/issues/1611, this was determined to be the public name, and with the addition of PhET-iO in preferences, we will want to make the code and tandem names match that decision. Tagging @jbphet so he is aware, but I'm planning to do this work.

**Comment by zepumph** [comment]
The only spot that wasn't trivial is that "enhancedSound" is in one joist string key:

https://github.com/phetsims/joist/blob/728b22344287518c21b673d701381f4abed6a74e/joist-strings_en.json#L32

I didn't change the key, but I did change the english value. I don't think we want to change the key, but it is a discrepancy. Otherwise, everything went very smoothly. I tested sims that support this through the menu item (GFL), and also those that do so through the preferences dialog (GFLB and RAP). I also see that phetmarks and package.json files all look good. @jbphet will you please do a spot check here. Thanks

**Comment by jbphet** [comment]
@zepumph said:
 > I didn't change the key...

I agree that we shouldn't change the key and should just live with the discrepancy.  If we were to change the key, we would need to adjust all existing translations of this string, or basically break the translation of it.  So leaving it unchanged seems better.

Closing.
