### ISSUE TITLE
Add support for reducing output while Voicing is announcing

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/tambo#167]
This came up recently in https://github.com/phetsims/quadrilateral/issues/185. Design would like sound to reduce its output while SpeechSynthesisAnnouncer is speaking content.

SpeechSynthesisAnnouncer has `startSpeakingEmitter` and `endSpeakingEmitter` that we could add listeners to to update the global volume. @jbphet do you have any thoughts about how to support this in tambo?

**Comment by jbphet** [comment]
@jessegreenberg - I implemented ducking in https://github.com/phetsims/quadrilateral/issues/185 and https://github.com/phetsims/tambo/issues/172 and it seems to be working well so far.  This issues seems like a duplicate.  Is it, and can it be closed?

**Comment by jessegreenberg** [comment]
Yep, thanks!
