### ISSUE TITLE
Memory leak reviews

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/tambo#176]
In https://github.com/phetsims/solar-system-common/commit/d9d7b51d13650fd169de2b65c43ef1ac4054e353, I noticed that enableControlProperties created from addSoundGenerator stick around after removeSoundGenerator. This seems a bit wrong. I added disposal of the soundClips themselves, since that clears the array and handles the memory leak.

However then I noticed another leak of DisplayedProperty in soundManager (we create it on addSoundGenerator, and don't dispose it). I'm working on patching that.

@jbphet can you review the associated commits, and let me know if the asymmetry for enableControlProperties is warranted?

**Comment by jonathanolson** [comment]
Added a map so I can clean up the leak in soundManager above.

**Comment by jbphet** [comment]
I looked this over and the functionality looks good.  I made some minor editorial changes.  Good to go, closing.
