### ISSUE TITLE
CT Cannot read properties of null (reading 'minimumWidth')

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#177]
```
tambo : multitouch-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1678892622491/tambo/tambo_en.html?continuousTest=%7B%22test%22%3A%5B%22tambo%22%2C%22multitouch-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1678892622491%22%2C%22timestamp%22%3A1678898392254%7D&brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Query: brand=phet&ea&fuzz&fuzzPointers=2&memoryLimit=1000&supportsPanAndZoom=false
Uncaught TypeError: Cannot read properties of null (reading 'minimumWidth')
TypeError: Cannot read properties of null (reading 'minimumWidth')
at minimumWidth (AquaRadioButton.ts:268:38)
at layout (LayoutConstraint.ts:201:13)
at updateLayout (LayoutConstraint.ts:215:11)
at listener (TinyEmitter.ts:102:8)
at emit (TinyProperty.ts:125:9)
at notifyListeners (TinyProperty.ts:73:11)
at set (TinyProperty.ts:59:9)
at (WidthSizable.ts:235:12)
at listener (TinyEmitter.ts:102:8)
at emit (TinyProperty.ts:125:9)
id: Bayes Puppeteer
Snapshot from 3/15/2023, 9:03:42 AM
```

**Comment by pixelzoom** [comment]
It looks like this started 3/14/23 @ 4:3158PM, if that helps.  And it's happening on almost every CT cycle.

**Comment by jbphet** [comment]
I wasn't able to duplicate this locally with about 1/2 hr of fuzz testing, but when I look at the line where the error occurs (`AquaRadioButton.ts:268:38`), it looks like code that was added right about the time the problem started.  The commit was https://github.com/phetsims/sun/commit/3116f99d1e35c12321f435a67fc0a631d02b2a7e, and it was made by @jonathanolson, so I'm going to assign it to him to have a look.  It appears that there is some path through the code where `this.radioNode` is not defined, but that's about all I can say at this point.

**Comment by jonathanolson** [comment]
Disposal essentially removes the child connection. We should dispose the constraint so it doesn't try to run layout code after disposal. @jbphet can you verify the fix above?

**Comment by jbphet** [comment]
Looks reasonable to me, and tambo is now passing CT.  Closing.
