### ISSUE TITLE
Should the sonification support be added to all sims, or just the sims where it is being used?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#18]
The title states the essential question.  The tradeoffs are:

+ Adding it to all sims will increase the size by some amount and possibly the load time, since the sound manager will be creating an audio context, some gain stages, and convolver, etc.  This could be moved into the initialize call if desired.
+ Adding it only to simulations that use it will cause Sim.js to be a bit more complicated, and the main file for the sim (e.g. build-an-atom-main.js) will have additional code as well to pass in the sonification manager.

I'll gather some data, then put this on the agenda for the next framework design meeting.  For now, I'm going with the "add it only when it is being used" approach to minimize impact on existing sims.

**Comment by jbphet** [comment]
I temporarily configured two sims, Charges and Fields (CAF below) and Color Vision (CV below), for sound support and quantified how much larger the built sim was, how much more memory it used, and how much longer it took to load.  I used these two sims because they are single screen, so they have already initialized a screen once loaded, and also because neither has any sound support at the moment.

When doing this testing, I used the query parameters that enable both sound support and enhanced sound selection.  The URL looked like this: 

```http://localhost:8080/charges-and-fields/build/phet/charges-and-fields_en_phet.html?tambo&supportsEnhancedSound```

...and the nav bar controls were definitely showing, like this:

![caf-with-sound](https://user-images.githubusercontent.com/3082831/42542214-1300ee68-8463-11e8-8d52-8722df77b686.png)

Here are the results of my testing:

Config | built size (kB) | mem usage after load (MB) | load time Win10 & Chrome (s) | load time iPad 2 (s)
--- | --- | --- | ---  | --- 
CAF w/o sound | 1548 | 14.6 | 2.85 | 6.82
CAF with sound | 1584 | 15.2 | 4.15 | 9.95
CV w/o sound | 1984 | 16.8 | 2.60 | 7.45
CV with sound | 2020 | 17.3 | 3.09 | 9.40

The data for the file size and memory usage are pretty consistent between sims, so the addition of the sound manager requires 36kB of file size and about 550 kB of browser heap memory.

The browser load time testing was less repeatable based on what I saw when working out the testing approach, so these numbers should be taken with a slight grain of salt.  The additional initialization associated with the sound manager added about 1 second to the load time on my Win 10 machine in Chrome (I used a fresh incognito window in an attempt to make this as repeatable as possible) and about 2.5 seconds to the load time on an iPad 2 (I used a fresh private browser tab to also make this as repeatable as possible).

**Comment by jbphet** [comment]
Marking for developer meeting to decide whether to add the code to joist in such a way that all sims include this library (which is less complicated but incurs the costs described above) or such that only the sims that need it include this library (more complicated).

**Comment by pixelzoom** [comment]
My understanding is that all sims will _eventually_ have sound, the same way that all sims will eventually be accessible, be instrumented for phet-io, etc.  So longterm, the answer is "yes", include this code in all sims and initialize the sound manager at startup.  But in the meantime...

Is it advantageous to keep this code out of sims that don't use it? Or skip initialization of sound?   If yes, then could we load/initialize only when "tambo" is specified (via query parameter or `Sim` option) ?

**Comment by samreid** [comment]
3 seconds longer on iPad sounds like a lot. How many runs did you do to obtain for these numbers (or just one sample each)?  How can I reproduce these results?

**Comment by jbphet** [comment]
Consensus during meeting:
+ Go for always included, selectively initialized
+ Publish dev versions of CAF and CV that support this (one offs)
+ Consider adding some logging that will back it easier to evaluate the cost of initializing the sound manager
+ Have QA gather load time data on all supported platforms

**Comment by jbphet** [comment]
I have published snapshots of Charges and Fields and Color Vision prior to adding any sound support so that we can use them as baselines for comparison as this feature gets added.  Please see:
+ Charges and Fields: https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.5/phet/charges-and-fields_en_phet.html
+ Color Vision: https://phet-dev.colorado.edu/html/color-vision/1.3.0-dev.1/phet/color-vision_en_phet.html

**Comment by jbphet** [comment]
I just realized that I made a mistake above in comment https://github.com/phetsims/tambo/issues/18#issuecomment-403996200 - Color Vision is not a single screen sim.  Still, using it seems to have worked fine for some of the assessments, and perhaps it's good to have one single-screen and one multi-screen sim, so I'm going to continue using it.

**Comment by samreid** [comment]
> I took some time to track this down, and almost all of the memory usage can be traced to the FontAwesomeNodes used in the NavigationBarSoundToggleButton. 

I wanted to try to reproduce this problem on my side, but after checking out joist "sound-control" branch and trying to launch Charges and Fields, I got this error:

GET http://localhost/charges-and-fields/js/TAMBO/soundManager.js?bust=1531840852811 404 (Not Found)

**Comment by pixelzoom** [comment]
@jbphet said:
> ... almost all of the memory usage can be traced to the FontAwesomeNodes used in the NavigationBarSoundToggleButton. . This seems excessive, and I think we will need to look at coding our own version of this icon using Scenery nodes.

Leveraging font-awesome icons is very valuable, so I disagree that we should jump immediately to "coding our own version".   I find it difficult to believe that the small number of icons that we're using are responsible for 4MB.   I suspect that we're paying the price for icons that we're not using.   And that's because of how FontAswesomeNode is implemented, not anything inherent in the icons.    So let's start by investigating how to load only the icons that we need.

**Comment by samreid** [comment]
> I find it difficult to believe that the small number of icons that we're using are responsible for 4MB

Indeed FontAwesome.js includes 21 icons and is only 14KB.

**Comment by pixelzoom** [comment]
@jbphet said:
> ... ... almost all of the memory usage can be traced to the FontAwesomeNodes used in the NavigationBarSoundToggleButton. 

How did you determine this?

**Comment by jbphet** [comment]
> Indeed FontAwesome.js includes 21 icons and is only 14KB.

Memory usage (i.e heap space), not code size.

> How did you determine this?

I ran the test with Font Awesome nodes for the icons, then replaced those icons with plain Scenery rectangles, and found that the former used almost 4MB of additional heap space.

> I suspect that we're paying the price for icons that we're not using.

This may well be true, i.e. loading one Font Awesome node causes them all to be interpreted.  I'll investigate.

> I wanted to try to reproduce this problem on my side, but after checking out joist "sound-control" branch and trying to launch Charges and Fields, I got [an] error...

You can resolve this error by either running the tambo demo, or run your sim of choice by adding TAMBO to the <sim-name>-config.js file.  To get the sound control icon, you need to include the "tambo" query param (available as a check box from phetmarks) in the URL.

**Comment by samreid** [comment]
Thanks @jbphet, I'm seeing the same 4MB you referred to, tested over 3 trials:

![image](https://user-images.githubusercontent.com/679486/42834123-67a48b46-89b3-11e8-84c8-11f90273f8d3.png)

But I cannot easily tell from the heap comparison that the difference is due to font awesome.

**Comment by samreid** [comment]
I also replaced the FontAwesomeNode with Rectangle and saw the heap sizes change:
?tambo: 19.3MB
without: 19.0MB

**Comment by samreid** [comment]
@jbphet and I worked on this and isolated the 4MB memory usage to the volume up icon.  When running a sim with the volume up icon it runs 4MB higher than when using the volume down icon.  Perhaps kite/scenery ends up creating extra things for rendering the sound waves (that is an 887 character SVG path compared to 158 character for volume down).  @jbphet said he is coordinating with @pixelzoom to try a scenery version.

**Comment by jbphet** [comment]
Sorry - I did say "Chris", but I meant @chrisklus.

**Comment by jbphet** [comment]
I published dev snapshots of CAF and CV, then merged in the sound-control branch, then published again.  The pre-merge snapshots are:
+ https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.5/phet/charges-and-fields_en_phet.html
+ https://phet-dev.colorado.edu/html/color-vision/1.3.0-dev.1/phet/color-vision_en_phet.html

The post-merge snapshots are:
+ https://phet-dev.colorado.edu/html/charges-and-fields/1.1.0-dev.6/phet/charges-and-fields_en_phet.html
+ https://phet-dev.colorado.edu/html/color-vision/1.3.0-dev.2/phet/color-vision_en_phet.html

The post-merge snapshots include the tambo sound library, but the library is not initialized unless the `tambo` query parameter is included in the URL.  Below is a table that shows the size and memory usage for each configuration.

This table does NOT include load times.  I'll set up a QA task to gather that information.

Config | built size (kB) | mem usage after load (MB) 
--- | --- | --- 
CAF before merge | 1544 | 14.0 
CAF after merge, sound off | 1584 | 14.2 
CAF after merge, sound on | 1584 | 14.5 
CV before merge | 1980 | 16.2 
CV after merge, sound off | 2020 | 16.5 
CV after merge, sound on | 2020 | 17.0

These numbers are pretty consistent with the original tests, and show that memory usage is decreased by about 300-500 kB by doing "selective initialization".  Also, creating our own sound on/off icons saved a lot of memory versus using the FontAwesomeNode implementations.

These numbers seem pretty acceptable to me in terms of build size and memory usage.  The next step is to gather more details on the additional load time that this requires.

**Comment by jbphet** [comment]
Assigning to QA to gather data on how much additional load time is incurred by the sound library when both off an on on several of the most representative platforms that we support.  I spoke with @KatieWoe, and she suggested using a modified test matrix to collect the data, which sounds good to me.

**Comment by KatieWoe** [comment]
Testing Matrix:
https://docs.google.com/spreadsheets/d/1UJJBD0PAYkta0b1EaWktToXwPZm3e3sXWN1ktcUEmfE/edit?usp=sharing

**Comment by jbphet** [comment]
We reviewed the additional load times and concluded that it was acceptable.  Closing.
