### ISSUE TITLE
Duplicate grab sounds

### ISSUE THREAD

**Issue by zepumph** [phetsims/tambo#185]
Over in https://github.com/phetsims/scenery/issues/1592#issuecomment-1942189106 @jbphet and I agree that `grab2_mp3` is a great grab sound, and we only think we need one grab sound in the project. We recommend removing `grab_mp3`, and just using one for all grab cases. I'll take a look.

**Comment by zepumph** [comment]
@Ashton-Morris please let us know if you feel differently, or feel it is important to have both sounds available.

**Comment by zepumph** [comment]
There were 3 usages of `grab2_mp3`, and 8 usages of `grab_mp3`. They are now all using `grab2_mp3`, but it has been renamed to grab_mp3 since the other was deleted. @Ashton-Morris does this sound good to you? Feel free to close if all is well.

**Comment by Ashton-Morris** [comment]
Sounds good to me! Closing.
