### ISSUE TITLE
ContinuousPropertySoundClip blows up when range.min === 0

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#188]
From https://github.com/phetsims/tambo/issues/187 ...

> ContinuousPropertySoundClip  blows up when range.min is 0, due to a divide-by-zero error in the code shown below. It’s not uncommon for a Property to have zero as its minimum valid value, and still want to produce sound. I hit this immediately in FEL for the compass (0 angle) and field meter (0G magnet). That makes ContinuousPropertySoundClip unusable for me. If it’s a constraint that can't be overcome, add `assert( range.min !== 0 )` for now, so it doesn’t blow up downstream.

```ts
const normalizedValue = Math.log( value / range.min ) / Math.log( range.max / range.min );
```

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/tambo/commit/117e925f35f957b859e133ec697a35919b82f45b, I added an assertion and a TODO that references this issue.  I've consulted wtih @jbphet and @zepumph on this, and there's no obvious way to fix this.  There are probably also cases where 0 for a Property value means "no sound".  Also worth noting these other problems mentioned in https://github.com/phetsims/tambo/issues/187#issuecomment-1952630009:

> After consulting with @jbphet, I'm going to avoid using ContinuousSoundClip. There are other big problems --it's designed to be wired into the model but not the view, it doesn't support fade in & out, it requires calling `step`,...

As is, I've made a mental note to avoid ContinuousSoundClip entirely in sims that I'm responsible for.

**Comment by marlitas** [comment]
Running into this with Mean Share and Balance as well. https://github.com/phetsims/mean-share-and-balance/issues/173

**Comment by jbphet** [comment]
I have changed the code and the API to handle arbitrary ranges for the monitored value and to map the values into a provided pitch range.  I also added a parameter to allow some variation in the mapping.  This enabled me to match quite closely all the previous usages of `ContinuousPropertySoundGenerator`.

I think this is good to go.  I'll finish integrating it into mean-share-and-balance and, if that works reasonably well, I'll close.

**Comment by jbphet** [comment]
I integrated an instance of this into mean-share-and-balance, but I think we're going to go a different direction for the use case that had been envisioned there.  It did function correctly though, so it should be ready to review.  @marlitas said she was up for it, assigning to her.

**Comment by marlitas** [comment]
I looked through the code changes and the approach seems reasonable. I will say I had a bit of a hard time following the switch between the `playbackRateOffset` option and the `normalizationMappingExponent`. Some of it might be my unfamiliarity with the science and math behind sound generation in general. Otherwise the changes seemed straightforward and appropriate and is working as expected. Back to @jbphet if you're ready to close.
