### ISSUE TITLE
document visibility of new query parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#21]
We agreed in a recent dev meeting to indicate whether query parameters are internal or public facing.  This was not done for the new `tambo` and `supportsEnhancedSound` query parameters.  

I've been documenting like this:

```js
    /**
     * Blah blah blah.
     * For internal use only.
     */
    someQueryParameter: ...

    /**
     * Blah blah blah.
     * Public facing.
     */
    anotherQueryParameter: ...
```

**Comment by jbphet** [comment]
Done, closing.
