### ISSUE TITLE
Add a query parameter to disable sound

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#25]
In https://github.com/phetsims/vibe/issues/28, we decided to add a query parameter that would turn sound all the way down regardless of what the user did.  This was originally motivated by the desire to keep sounds from startling the bejesus out of us when doing automated fuzz testing, but we made the query parameter public and may have let outside users know about it.

We'll need this functionality - or some variation of it - in the tambo library.  I personally would prefer just a flag that would completely remove support for sound, including preventing the icon from showing up on the nav bar, instead of a value that would turn the sound down.  The latter seems like it could be confusing to users.

You may be inclined to ask why we can't use the current query parameter that enables sound.  The reason is that this query parameter is intended to be override-able by the sim configuration, so it couldn't be used to disable the sound in a fully sound-enabled simulation.

My proposal is to add a query parameter flag called `preventSound` that, if present, would prevent the sound icon from appearing on the nav bar, would prevent the "Enhanced Sound" option from appearing in the PhET menu, and would prevent any sound from being generated.

Assigning to @emily-phet and @ariel-phet for input.  We can make this a design meeting topic at some point if needed.

**Comment by ariel-phet** [comment]
@jbphet I think a flag is fine. However, would having a flag remove the ability to have a query parameter? If a teacher wants to be able to bring a sim up for the class with sound enabled/disabled that might be a nice configuration in the future as we begin to reveal more query parameters to the public.

**Comment by jbphet** [comment]
> [W]ould having a flag remove the ability to have a query parameter?

A flag is a type of query parameter (in this context).  It's one that doesn't need a value, so it would be used like `<sim-url>?preventSound` versus something like `<sim-url>?soundAllowed=false`.

> If a teacher wants to be able to bring a sim up for the class with sound enabled/disabled that might be a nice configuration in the future as we begin to reveal more query parameters to the public.

Exactly.  It would help us in the short term for testing, and it would likely be something that teachers would want at some point, especially when sound is on by default for lots of sims.

**Comment by emily-phet** [comment]
Sounds good to me - we already have a scenario where this would be useful. We're planning user interviews where we would like to have the user explore a sim that has sound, but without the sound first. Then the user would explore with sound. This will allow us to get at some feedback on description specifically (our main focus for the interview), without complicating that initial discussion with sound.

**Comment by jbphet** [comment]
Superseded by https://github.com/phetsims/tambo/issues/47, closing.
