### ISSUE TITLE
Consider changing query parameter from "tambo" to "supportsSound"

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#26]
While @samreid and I were working on the integration of the sound controls into joist, he suggested that we change the query parameter and configuration flag to enabled sound support from "tambo", which reflects the library name, to "supportsSound".  I quite like this.  The downside is that it could potentially be confusing in pre-tambo sims with sound support, since they would still support sound even without this query parameter or configuration option.  

I'd like to discuss in the next dev meeting and, unless there are strong opinions against the use of "supportsSound", I'd like to go with that.  I think developers can handle the potential confusion, and the code with this flag will be easier to understand in the long run.

**Comment by samreid** [comment]
When https://github.com/phetsims/vibe/issues/33 is complete (which is already demonstrated in a branch), Vibe will be implemented with Tambo and hence the query parameter will still make sense.

**Comment by jbphet** [comment]
> When phetsims/vibe#33 is complete (which is already demonstrated in a branch), Vibe will be implemented with Tambo and hence the query parameter will still make sense.

This is kind of true, but not entirely.  The query parameter is only intended to be used during the period that sound is being added to a sim.  This will allow us to publish from master if we have to without including a partially implemented sound design that is audible to users.  Once the sound is fully implemented for a simulation, the corresponding flag will be set in the Sim options, and sound will always be enabled.  The query parameter will have no effect at this point.  Since the sims that currently use vibe already have sound, we would set the flag in that sim's options, and the query parameter would not be used.

**Comment by jbphet** [comment]
I'll be unavailable for the next developer meeting, but I'd still like to see if the group can come to consensus as to whether changing the query parameter as described is acceptable.  I'm bringing it up to the group because something like this was originally suggested, but there were concerns about confusion between support for sound using the old, simpler library (vibe) and the new more feature-rich one (tambo).  My own preference would be to migrate to `supportsSound` or something similar that conveys the idea on its own instead of `tambo`, that only means something to those who know what that library is.

**Comment by jonathanolson** [comment]
I don't have any objections.

**Comment by Denz1994** [comment]
I don't have a problem with changing the query parameter, but if we are flexible with the name ```supportsSounds```, I would suggest ```sonify``` or ```sonified```. ```supportsSounds``` doesn't seem specific to tambo or vibe since both libraries support sound.

**Comment by jessegreenberg** [comment]
Without knowledge of context I would expect `supportsSound=false` to disable all sounds including those of `vibe` in the short term. I like `sonify`, but I have also heard that we are trying to not use "sonification" for this work as much. Maybe `tamboSound` or `enhancedSound`?

**Comment by zepumph** [comment]
I see in phetsims/vibe#33 that having vibe run on tambo would cut support for IE. If we continue to support IE, then we may continue to have vibe run sound separately.

>The downside is that it could potentially be confusing in pre-tambo sims with sound support

I agree, and I don't see a need to muddy these waters for this internal query parameter. That said, if we dropped support for IE and made tambo synonymous for all sim sound, then I think the new query parameter name would very good.

That said, I still don't have a strong preference, and I trust @jbphet to make the right decision since he is lead dev.

**Comment by jbphet** [comment]
This has been done, closing.
