### ISSUE TITLE
Tambo crashes in Windows 8.1 and 7 IE11

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/tambo#27]
**Test device:**
Schrodinger and Bates
**Operating System:**
Windows 8.1 and 7
**Browser:**
IE 11
**Problem description:**
When trying to take away balls in the first tambo screen the sim crashes. For phetsims/QA/issues/160
**Steps to reproduce:**
1. Go to the first screen. Have the console open.
2. Add several balls to the box
3. Try to take one away

Screenshot:
![img_0234](https://user-images.githubusercontent.com/31285590/43663054-4e05d260-9725-11e8-9635-2c7614a67443.JPG)

[Video](https://drive.google.com/open?id=1g3ja8Kcacz7YnkiH--DFHYqZLpNPyHUa)

**Comment by jbphet** [comment]
@KatieWoe - this should now be fixed on master, can you please verify and, if no longer crashing, close this issue?

**Comment by KatieWoe** [comment]
Confirmed on both Windows 7 and 8
