### ISSUE TITLE
Description of Tambo for annual report

### ISSUE THREAD

**Issue by emily-phet** [phetsims/tambo#29]
@jbphet 
I'm writing the annual report for the grant that funds the sonification work. I'd like to include a section that describes Tambo. Could you draft up a 1-page document that includes a:

- Brief description of the relationship between Tambo and phet’s overall infrastructure
- Brief description of how Tambo is structured
- Summary or list of affordances of Tambo (for example, the relevant features it supports that we found necessary from the sonification work as a whole).

Audience:
Option 1) Try to target this towards a lay audience, though it's ok if some parts won't be completely understandable to everyone. The idea is to convey an idea of what was created under this grant, not that the reader should be able to utilize this information directly in their work. 

Option 2) Alternately, you might consider if this type of information (written with developers in mind) would be useful for some supporting documentation on GitHub. If that's the case, could can write a version for GitHub, and I can adapt (reword/simplify) for the grant report.

If you could get your text to me by August 29th, that should leave me enough time to adapt or revise the text before including it in the report (to be submitted Sept. 4th).

Of course, let me know if you have any questions, concerns!

**Comment by jbphet** [comment]
I spoke with @emily-phet about this, and she said that the writeup is actually needed sooner than August 29th, so I'll be working on it today, August 22 2018.

**Comment by jbphet** [comment]
@emily-phet - I've written a page, please take a look at https://docs.google.com/document/d/1aJxDVnLsxyyG5MZvMoVr4dJCWGIS3FPJaINSVwP8teQ/edit?usp=sharing and let me know if this will work and if you'd like me to make some changes.

**Comment by jbphet** [comment]
I talked with @emily-phet and she has made edits and is good with what we've got.  Closing.
