### ISSUE TITLE
Prevent appearance of sound control nav bar button on IE

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#32]
In https://github.com/phetsims/tambo/issues/6 we decided that we will stop supporting sound on IE when the sonification library is integrated into the mainline sims.  We are in the process of doing this integration now, and in the 8/23/2018 dev meeting we decided that the sound control button shouldn't appear at all on IE so that users aren't confused.

**Comment by jbphet** [comment]
Done, but I'd like to leave this open and have it verified by QA on the first RC of a sim with sound support.

**Comment by KatieWoe** [comment]
Unable to test on 1.5.0-rc.1 due to https://github.com/phetsims/john-travoltage/issues/314.  Should be tested in next rc

**Comment by jbphet** [comment]
This has been verified (a while ago).  Closing.
