### ISSUE TITLE
Scratchy and distorted audio on iPad 2

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#33]
This was reported during multi-platform testing of a dev version of the tambo demo, see https://github.com/phetsims/QA/issues/160#issuecomment-410363408.

**Comment by jbphet** [comment]
I did a bunch of debugging and online research, an it appears that the problem is due to a bug in some versions of iOS where the audio context will change its sample rate to 48000 if anything is played at that rate, and then all subsequent playback of sounds that have a 44100 rate - or, for that matter, any playback from oscillators that were created when the rate was 44100 - has distorted audio.  Here are some links with more information:

+ https://stackoverflow.com/questions/29901577/distorted-audio-in-ios-7-1-with-webaudio-api
+ https://github.com/Jam3/ios-safe-audio-context
+ https://stackoverflow.com/questions/34427162/buzz-on-ios-9-2-with-audiocontext-web-audio-api

**Comment by jbphet** [comment]
I have added somewhat of a fix, but it feels a bit fragile.  I re-encoded some sounds that were using a 48 kHz sample rate so that none of the sounds used in the tambo demo use this rate, and this fixed almost all of the problems with the distorted sound.  However, I was still able to break sound production by using the memory testing on the 3rd screen to add a bunch of synthesized sound generators.  This is a bit of an unrealistic scenario - we're not likely to be creating lots of sound generators without disposing of others.  And, the tambo demo already adds a ton of sounds because of the encoding testing.  In other words, I'm not overly concerned that the extremes of the tambo demo can cause sound issues on iPad 2.  What we will need to do is to check sims to which sound has been added and make sure that we don't hit these boundaries and start generating distorted sound on iPad 2.

**Comment by pixelzoom** [comment]
@jbphet I'm not sure why @ariel-phet changed the label on this issue, there's no comment.  But now the issue is ready-for-review and unassigned, and there has been no progress since May 2019.   So back to you to decide how to proceed.

**Comment by jbphet** [comment]
Thanks for reviving this @pixelzoom - we should definitely try to close the loop on it.

@KatieWoe - This issue was reported on iPad 2, which is no longer supported.  I've done a fair amount of testing on the device that is currently available to me, which is unnamed iPad 4 A2270 (this is a pretty new device) and have never encountered the issue.  I think we should have QA test on our current batch of iPads and, if the problem no longer exists, the issue can be closed.

This is not a high priority issue, so I think it can probably be done in the "spaces" between other higher priority testing when there is a lull.

**Comment by KatieWoe** [comment]
Sounds good. Can you make an issue for the test in the QA repo?

**Comment by jbphet** [comment]
Issue https://github.com/phetsims/QA/issues/613 has been set up for this testing.

**Comment by jbphet** [comment]
QA has tested on our current set of devices and found that this is no longer a significant problem.  Closing.
