### ISSUE TITLE
Gaps or glitches in loops on different platforms

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#35]
Loop sounds that sound good on one platform often have a gap or a click when tested on another (e.g. Chrome vs Firefox on my Win 10 machine).  There is a lot of talk on line about how different mp3 decoders insert different amounts of silence when encoding, and I suspect that there is a similar effect from different decoders.

**Comment by jbphet** [comment]
I've added code that detects and sets the beginning and end of the loop, and the situation is much improved, but it was points out that on the sonified version of JT that we are mixing on (https://phet-dev.colorado.edu/html/john-travoltage/1.5.0-dev.2/phet/john-travoltage_en_phet.html?supportsSound&supportsEnhancedSound), a glitch can still be heard, so we're not quite there yet.

**Comment by KatieWoe** [comment]
Everything sounds good.  Closing
