### ISSUE TITLE
Cannot read property 'autoDetectLoopBounds' of undefined

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#37]
This CT failure is occurring regularly in tambo and sporadically in various other repositories (graphing-slope-intercept, gravity-force-lab-basics, john-travoltage, wave-interferences, wilder, ...) 

> tambo : fuzz : require.js : run
Uncaught TypeError: Cannot read property 'autoDetectLoopBounds' of undefined
TypeError: Cannot read property 'autoDetectLoopBounds' of undefined
    at AudioContext.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1535928147520/tambo/js/sound-generators/SoundClip.js?bust=1535971538352:60:22)
Approximately 9/2/2018, 4:42:27 PM

**Comment by jbphet** [comment]
I'd messed up the options pattern, should be fixed now.  I'll leave this open and double check tomorrow the all CT tests are passing.

**Comment by jbphet** [comment]
I'm no longer seeing any failures on CT, closing.
