### ISSUE TITLE
ES6 conversions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#42]
Related to code review https://github.com/phetsims/tambo/issues/39.  This will be a list of ES6 conversions to consider.  I'll be editing this list while I'm doing the code review.

- [ ] `define( function( require ) {...}` to `define( require => {...} )`
- [ ] `inherit` to `class`
- [ ] `return tambo.register( 'foo', foo )`
- [ ] get rid of `self` where not needed
- [ ] get rid of `function` where you can

**Comment by pixelzoom** [comment]
Code review is done, my list above is complete.  There are probably some other ES6 features that you could use for the sake of using them (spread operator, destructuring) but I really don't see the point unless it makes your code remarkably clearer.

**Comment by SaurabhTotey** [comment]
I believe the entirety of this simulation is now in ES6. I am closing this issue, but feel free to reopen if I have missed anything.
