### ISSUE TITLE
query parameter names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#44]
Related to code review https://github.com/phetsims/tambo/issues/39.

initialize-globals.js contains query parameters `soundInitiallyEnabled` and `enhancedSoundInitiallyEnabled`, used exclusively in soundManager.js.  I think it would be fine to drop the "Initially" part of these names.  It would still be obvious what they are for, and it would be less verbose.

**Comment by jbphet** [comment]
This was a good reminder.  This feature is not quite finished.  In the 8/30/2018 design meeting we decided to have a 'sound' parameter that can be set to 'enabled' (the default), 'disabled', or 'muted'.  This would replace this functionality.  I'll log a separate issue for that, then close this one.
