### ISSUE TITLE
factor out helper functions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#45]
Related to code review https://github.com/phetsims/tambo/issues/39.

SoundClip.js contains some private "helper" functions that are related to finding where sound starts and ends, etc.  The functions are `findSoundStartIndex`, `findSoundEndIndex`, `detectLoopBounds`, and (possibly) `logLoopAnalysisInfo`.   Consider moving these functions to another file, something like SoundUtils.js or whatever name you feel accurately describes this collection of helper functions.

Factoring out these functions would reduce the size of SoundClip.js by 100+ lines.

**Comment by jbphet** [comment]
Done as described.  Closing.
