### ISSUE TITLE
Add support for a 'sound' query parameter

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#47]
In the 8/30/2018 sonification design review meeting we collectively decided on an approach to handling some query parameter support for the sound feature.  The current plan is to have a 'sound' parameter that can be set to 'enabled' (the default), 'disabled', or 'muted'.  Enabled would be the case where sound is initially enabled.  The 'disabled' value would mean that sound is not available at all, and the icon to control is would not be present on the nav bar.  The 'muted' value would mean that sound is available in the sim, but is initially muted and must be un-muted by the user by clicking the nav bar control.

**Comment by KatieWoe** [comment]
Seems good to go 1.5.0-rc.1
Closing.

**Comment by jbphet** [comment]
During the testing, @KatieWoe showed me that having just "sound" as the parameter with no assigned value causes sound to be disabled.  This isn't what we want.  After talking with other devs, I found out that I can specify valid values for this, and if one isn't set, it will stop the sim from loading.  I'm going to implement this.

**Comment by jbphet** [comment]
Note to self: This should go into the next RC of John Travoltage.

**Comment by jbphet** [comment]
Addressed, closing.
