### ISSUE TITLE
tambo dependency broke the instructions in "PhET Development Overview" 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#54]
In https://github.com/phetsims/chipper/commit/688f8993c0ff3171cda26ef23ed1a2330558c154, @jbphet added tambo as a dependency for all sims.   That new dependency has broken instructions in the "Getting Started" instructions in the [PhET Development Overview](https://docs.google.com/document/d/1Ys1EiwnqQGYuzGOcQSr4uXDes35mF1v1XhMZIl10nk8/edit#).  It's necessary to clone tambo.   

This issue was encountered in [this thread](https://groups.google.com/forum/#!topic/developing-interactive-simulations-in-html5/o4YeM9OKUT8) in the Google Group, where a group member reported that he was unable to run example-sim after following the instructions.

There may be other instructions (jn the same doc or in other docs) that are also broken.

**Comment by pixelzoom** [comment]
I've fixed step 2d of the "Getting Started (Windows)" and "Getting Started (macOS)" section of the "PhET Development Overview" by adding:

`git clone https://github.com/phetsims/tambo.git`

@jbphet please consider whether there are other documents that need to be updated.

**Comment by pixelzoom** [comment]
I did a search of "git clone" across all PhET files in GitHub, and I don't see any other places where `git clone .../tambo.git` is missing.   

Are the any other Google docs, similar to "PhET Development Overview"?

**Comment by jbphet** [comment]
Thanks @pixelzoom for the fix to the development overview docs.  I don't know of any similar documents, and I did the same search you did and didn't find anything additional.  I think it's safe to close, please reopen if you disagree.
