### ISSUE TITLE
use standard layoutBounds in tambo demo

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/tambo#55]
Related to https://github.com/phetsims/joist/issues/542.

For some reason, the tambo demo was implemented using non-standard layoutBounds (and non-standard aspect ratio) for all ScreenViews.  This is typically only done for sims that are ported from Java.

**Comment by pixelzoom** [comment]
In the above commits, the tambo demo is now using the default ScreenView layoutBounds.  I've adjusted font sizes, spacing, etc. to be approximately the same as before this change.  Since this is a demo application, I did not attempt to make this even close to pixel perfect -- it's in the same ballpark. Assigning to @jbphet to verify that he's happy with the end result.

**Comment by jbphet** [comment]
The end result looks fine, thanks.  I don't recall choosing custom layout bounds, so my guess is that I copied the screen view from some other demo or sim.  At any rate, it all looks good, so I'll close the issue.
