### ISSUE TITLE
Update license annotations for new sound files

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#69]
In 79bbb07c04691515d65843c0a08d4f9f5b6e33f0 several new audio sounds were added.  Corresponding license entries were not added, and this is showing on CT.

![image](https://user-images.githubusercontent.com/679486/58849689-9067cd80-8648-11e9-9005-2de1c62afe56.png)

I'll add stubs for the entries, but I don't know the authors or other notes, so that should be added.

**Comment by jbphet** [comment]
Thanks @samreid, and my apologies for neglecting these entries and breaking CT.  I've added the license notes, so this should be good to go.  Closing.
