### ISSUE TITLE
Did we want a sound other than a radio button sound to play when you select different scenes in a sim?

### ISSUE THREAD

**Issue by Ashton-Morris** [phetsims/tambo#71]
I can't remember what we decided @emily-phet but we talked about it in a general sound meeting. Did we want a sound other than a radio button sound to play when you select different scenes in a sim?

ex: https://phet.colorado.edu/sims/html/masses-and-springs/latest/masses-and-springs_en.html

It does seem like a more important thing than a radio button option but I'm not sure what we decided. Also, what about for the home icon?

**Comment by emily-phet** [comment]
@Ashton-Morris - yup, having a related - but different - sound for scene selection buttons would be nice. Scene selection is a relatively significant change within a sim. I'd put it at Reset all > scene selection > local reset > radio buttons > checkboxes (for some sims, radio buttons/checkboxes may be switched or equivalent).

**Comment by Ashton-Morris** [comment]
Thanks
