### ISSUE TITLE
Using enabled properties and the associatedViewNode option seem to cut volume

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#74]
While working on the sound design implementation for Waves Intro, @samreid encountered some problems while trying to set up the light beam sound to be off when the sound effect is disabled and when the laser is invisible.  The sound seemed to be unexpectedly quiet in these cases.  Here is an excerpt from the code that shows where the problem was encountered:

```js
          // TODO: @jbphet: the following line cuts the audio by about half when used instead of using the multilink below
          // TODO: @jbphet: also note when I added associatedViewNode: view this also cut the volume approximately in half
          // lightBeamLoopSoundClip.addEnableControlProperty( model.lightScene.soundEffectEnabledProperty );
          soundManager.addSoundGenerator( lightBeamLoopSoundClip, {
            associatedViewNode: view
          } );

          const lightAmplitudeProperty = model.lightScene.amplitudeProperty;
          const lightFrequencyProperty = model.lightScene.frequencyProperty;
          Property.multilink( [ lightAmplitudeProperty, lightFrequencyProperty ], ( amplitude, frequency ) => {
            const outputLevel = Util.linear( lightAmplitudeProperty.range.min, lightAmplitudeProperty.range.max,
              0.0, 0.8, amplitude );
            const playbackRate = Util.linear( lightFrequencyProperty.range.min, lightFrequencyProperty.range.max,
              1, 1.8, frequency );
            lightBeamLoopSoundClip.setOutputLevel( outputLevel );
            lightBeamLoopSoundClip.setPlaybackRate( playbackRate );
          } );

          Property.multilink( [
            model.lightScene.button1PressedProperty,
            model.isRunningProperty,
            model.lightScene.soundEffectEnabledProperty
          ], ( button1Pressed, isRunning, enabled ) => {
            const shouldPlay = button1Pressed && isRunning && enabled;
            if ( lightBeamLoopSoundClip.isPlaying && !shouldPlay ) {
              lightBeamLoopSoundClip.stop();
            }
            else if ( !lightBeamLoopSoundClip.isPlaying && shouldPlay ) {
              lightBeamLoopSoundClip.play();
            }
          } );
```

**Comment by jbphet** [comment]
I was able to duplicate this problem by creating two different versions of Waves Intro, one that associated the `lightBeamLoopSoundClip` with the view of the light scene like so:

```
soundManager.addSoundGenerator( lightBeamLoopSoundClip, {
        associatedViewNode: view
      } );
```

...and one that did not make such an association, like this:

```
soundManager.addSoundGenerator( lightBeamLoopSoundClip );
```

The sound effect for the light beam was significantly louder in the first one.

I think I've figured it out, and it's a bit of a nasty problem.  The root of the issue is that setting the gain value for a Web Audio gain node using the `setTargetAtTime` method doesn't seem to work when the associated audio context is in the `suspended` state, which it is until the user interacts with the sim due to what are generally referred to as the "autoplay policies" of the various browsers.  The `setTargetAtTime` method is used in `SoundGenerator.setOutputLevel()`, and it was chosen because it is able to smoothly transition volume levels when they are being frequently updated, which can happen in some cases, such as the `FootDragSoundGenerator` in John Travoltage.  

Because the code in wave-interference is calling `setOutputLevel` during construction, which is somewhat unusual (usually we just specify the `initialOutputLevel` as an option for a sound generator), we encounter this problem, and as a result the gain level for `lightBeamLoopSoundClip` is not actually being set correctly *unless* there is some other enabled property or associated view node that changes before the sound is played, thus triggering an update to the gain level.  So, while it may be a bit uncommon, it should be perfectly fine to call `setOutputLevel` before the audio context is running, and tambo should handle it.

I tried changing `SoundGenerator.setOutputLevel()` to use the method `linearRampToValueAtTime()` instead of `setTargetAtTime()`, but because the linear method ramps from "the time specified for the previous event" (see the [online docs for this method](https://developer.mozilla.org/en-US/docs/Web/API/AudioParam/linearRampToValueAtTime)), it behaves oddly when used in rapid succession, and the `FootDragSoundGenerator` sounded horrible.  There is some discussion about this problem with Web Audio in general in various forums on the web, and apparently a method called `cancelAndHoldAtTime()` has been added to the Web Audio spec as a result, but as of this writing, Firefox, IE, and Safari don't support it.  So, I ended up adding a workaround that uses `linearRampToValueAtTime` if the audio context isn't running and `setTargetAtTime` if it is.  I tested this using the process described above for duplicating the issue, and the volume levels now seem consistent.  I also verified that they were using debug printouts that I didn't check in.

@samreid - I'm assigning this back to you so that you can try using an enabled-property approach if you like.  If you do, please record your results here.

**Comment by samreid** [comment]
I tried uncommenting
```js
lightBeamLoopSoundClip.addEnableControlProperty( model.lightScene.soundEffectEnabledProperty );
```
and it appeared to work OK.  Next I tried removing the code in the multilink that was handling that part and it was still OK.  So I decided to try using this approach for all Properties like so:


```diff
Index: js/waves/view/WavesScreenSoundView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/waves/view/WavesScreenSoundView.js	(revision 1d6d1cea4f016472c23306fcfafc3bd71a04db70)
+++ js/waves/view/WavesScreenSoundView.js	(date 1590532816028)
@@ -151,7 +151,9 @@
 
       // TODO: the following line was causing odd audio volume behavior, but this should now be addressed.  @samreid -
       // TODO: please try using it again, and report findings in https://github.com/phetsims/tambo/issues/74.
-      // lightBeamLoopSoundClip.addEnableControlProperty( model.lightScene.soundEffectEnabledProperty );
+      lightBeamLoopSoundClip.addEnableControlProperty( model.lightScene.soundEffectEnabledProperty );
+      lightBeamLoopSoundClip.addEnableControlProperty( model.lightScene.button1PressedProperty );
+      lightBeamLoopSoundClip.addEnableControlProperty( model.isRunningProperty );
       soundManager.addSoundGenerator( lightBeamLoopSoundClip, {
         associatedViewNode: view
       } );
@@ -170,20 +172,7 @@
         lightBeamLoopSoundClip.setOutputLevel( outputLevel * ducking );
         lightBeamLoopSoundClip.setPlaybackRate( playbackRate );
       } );
-
-      Property.multilink( [
-        model.lightScene.button1PressedProperty,
-        model.isRunningProperty,
-        model.lightScene.soundEffectEnabledProperty
-      ], ( button1Pressed, isRunning, enabled ) => {
-        const shouldPlay = button1Pressed && isRunning && enabled;
-        if ( lightBeamLoopSoundClip.isPlaying && !shouldPlay ) {
-          lightBeamLoopSoundClip.stop();
-        }
-        else if ( !lightBeamLoopSoundClip.isPlaying && shouldPlay ) {
-          lightBeamLoopSoundClip.play();
-        }
-      } );
+      lightBeamLoopSoundClip.play();
     }
   }
 }
```

This works correctly in the sim screen, but when you initially select the "Light" icon in the homescreen, there is a short burst of audio (note the call to `play()` during startup in the patch.)

If we still need a `link` or `multilink` then we may as well stick with the original strategy and treat all Properties equally.  And it did seem unconventional to call `play()` during startup, though it didn't add up that it would cause this burst of audio on the home screen when the icon is pressed.  @jbphet what do you recommend?

**Comment by jbphet** [comment]
I applied the patch above and tested, but I'm unable to duplicate the "short burst of audio".  I test in Chrome, Firefox, and Edge.  We should have a zoom call and take a look together.

I have seen some issues with sound glitches on the very first sound played by the sim before.  Is that what you're hearing?  If so, this is a result of the audio context changing states from "suspended" to "running" on the first user interaction.

**Comment by jbphet** [comment]
I met with @samreid via Zoom, heard what was going on, and spent some time trying to resolve it.  I come up with something that worked great on Chrome and Edge, but breaks sound entirely on Firefox.  Such is the nature of Web Audio at this stage of the game.  Below in the patch, but I'm not going to commit it (obviously).

I'm assigning this back to @samreid.  I recommend that for now you find some trigger to start and stop the loop when needed.  I suspect that it's not a great idea to leave a loop playing all the time anyway, because I would assume that uses browser resources, though it's hard to say how much.

@samreid - let me know if you'd like an issue for this in tambo and, if so, I'll create one.  Consider the possibility of a loop that is turned on and off via a set of properties if that might work better.

Patch:
```
Index: js/sound-generators/SoundGenerator.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/sound-generators/SoundGenerator.js	(revision 9c5f674c027fca9278a229b322cc9b99a62e035e)
+++ js/sound-generators/SoundGenerator.js	(date 1590616582352)
@@ -126,15 +126,24 @@
       const newGainSetting = fullyEnabled ? this._outputLevel : 0;
       const now = this.audioContext.currentTime;
 
-      // For the linear ramp to work consistently on all browsers, the gain must be explicitly set to what it is
-      // supposed to be before making any changes.  Otherwise, it may extrapolate from the most recent previous event.
-      this.masterGainNode.gain.setValueAtTime( previousGainSetting, now );
+      if ( this.audioContext.state === 'running' ) {
+
+        // For the linear ramp to work consistently on all browsers, the gain must be explicitly set to what it is
+        // supposed to be before making any changes.  Otherwise, it may extrapolate from the most recent previous event.
+        this.masterGainNode.gain.setValueAtTime( previousGainSetting, now );
 
-      // ramp the gain to the new level
-      this.masterGainNode.gain.linearRampToValueAtTime(
-        newGainSetting,
-        this.audioContext.currentTime + soundConstants.DEFAULT_LINEAR_GAIN_CHANGE_TIME
-      );
+        // ramp the gain to the new level
+        this.masterGainNode.gain.linearRampToValueAtTime(
+          newGainSetting,
+          this.audioContext.currentTime + soundConstants.DEFAULT_LINEAR_GAIN_CHANGE_TIME
+        );
+      }
+      else {
+
+        // The audio context isn't running, so set the gain value immediately.  This seems to cause the gain to go to
+        // the correct value as soon as the context starts running, which is what we want.
+        this.masterGainNode.gain.setValueAtTime( newGainSetting, now );
+      }
     } );
 
     // @private {function} - internally used disposal function
Index: js/soundManager.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/soundManager.js	(revision 9c5f674c027fca9278a229b322cc9b99a62e035e)
+++ js/soundManager.js	(date 1590616582383)
@@ -15,6 +15,7 @@
 
 import BooleanProperty from '../../axon/js/BooleanProperty.js';
 import Property from '../../axon/js/Property.js';
+import StringProperty from '../../axon/js/StringProperty.js';
 import merge from '../../phet-core/js/merge.js';
 import Display from '../../scenery/js/display/Display.js';
 import DisplayedProperty from '../../scenery/js/util/DisplayedProperty.js';
@@ -79,6 +80,8 @@
     // methods for more info
     this._reverbLevel = DEFAULT_REVERB_LEVEL;
 
+    this.audioContextStateProperty = new StringProperty( phetAudioContext.state );
+
     // @private {Object} - a map of category name to GainNode instances that control gains for that category name,
     // will be filled in during init, see the usage of options.categories in the initialize function for more 
     // information.
@@ -170,22 +173,33 @@
     // active
     Property.multilink(
       [
+        this.audioContextStateProperty,
         this.enabledProperty,
         window.phet.joist.sim.isConstructionCompleteProperty,
         simVisibleProperty,
         simActiveProperty,
         phet.joist.sim.isSettingPhetioStateProperty
       ],
-      ( enabled, simInitComplete, simVisible, simActive, simIsSettingPhetioState ) => {
+      ( audioContextState, enabled, simInitComplete, simVisible, simActive, simIsSettingPhetioState ) => {
 
-        const fullyEnabled = enabled && simInitComplete && simVisible && simActive && !simIsSettingPhetioState;
+        const fullyEnabled = audioContextState === 'running' && enabled && simInitComplete && simVisible && simActive &&
+                             !simIsSettingPhetioState;
         const gain = fullyEnabled ? this._masterOutputLevel : 0;
 
-        // set the gain, but somewhat gradually in order to avoid rapid transients, which sound like clicks
-        this.masterGainNode.gain.linearRampToValueAtTime(
-          gain,
-          phetAudioContext.currentTime + LINEAR_GAIN_CHANGE_TIME
-        );
+        if ( audioContextState === 'running' ) {
+
+          // set the gain, but somewhat gradually in order to avoid rapid transients, which sound like clicks
+          this.masterGainNode.gain.linearRampToValueAtTime(
+            gain,
+            phetAudioContext.currentTime + LINEAR_GAIN_CHANGE_TIME
+          );
+        }
+        else {
+
+          // The audio context isn't running, so setting the value for the current time should cause it to take effect
+          // as soon as the context starts.
+          this.masterGainNode.gain.setValueAtTime( 0, phetAudioContext.currentTime );
+        }
       }
     );
 
@@ -248,6 +262,8 @@
       let previousAudioContextState = phetAudioContext.state;
       audioContextStateChangeMonitor.addStateChangeListener( phetAudioContext, state => {
 
+        this.audioContextStateProperty.set( state );
+
         phet.log && phet.log(
           'audio context state changed, old state = ' +
           previousAudioContextState +
```

**Comment by samreid** [comment]
> Consider the possibility of a loop that is turned on and off via a set of properties if that might work better.

That is the current checked-in implementation.  Perhaps it will be part of the review in https://github.com/phetsims/wave-interference/issues/426.  Should this issue be left open and unassigned for now?

**Comment by samreid** [comment]
According to https://stackoverflow.com/questions/48317725/is-it-safe-to-run-multiple-instances-of-puppeteer-at-the-same-time/52596920 it is safe to run multiple puppeteers concurrently.

**Comment by jbphet** [comment]
I'll follow up on this by making sure that I review this section of the code, then will create a new issue since most of this one has been addressed, and then close this.

**Comment by jbphet** [comment]
Since the originally reported problem about the volume being reduced has been addressed, albeit with something a little awkward, I'm going to close this issue and have opened a new one about the audio burst and will follow up there.  The new one is #109.  Closing.
