### ISSUE TITLE
MultiClip should use Map

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#75]
In https://github.com/phetsims/wave-interference/issues/426#issuecomment-521374909 it was recommended that Wave Interference use MultiClip for the water drop sounds.  At the moment, the interface is `[{value:x,soundInfo:y}]` and MultiClip uses a search every time you try to play a sound:

```js
_.find( this.valueToAudioBufferMap, entry => { return entry.value === value; } );
```

In https://github.com/phetsims/tasks/issues/992#issuecomment-515168907 we agreed to allow `Map` in our code.  It seems MultiClip would be a good place to use Map.

**Comment by samreid** [comment]
If I understand correctly, https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map and https://github.com/phetsims/tasks/issues/992#issuecomment-507384524 indicate we cannot use `new Map([])` syntax because it is not supported on IE.  Perhaps we should use `Map.set` instead?  Or is this code already avoided because sound is not supported on IE?  In that case, it should be documented as such, like `// This code uses a Map constructor that doesn't exist on IE, but this code isn't triggered to run on IE anyways`

**Comment by jbphet** [comment]
Hmmm.  Well, that makes Map less appealing, but since I had already made the changes I went ahead and added explicit set operations.  Back to you @samreid.

**Comment by samreid** [comment]
Looks great, thanks!
