### ISSUE TITLE
Is license entry correct and can we use this impulse response?

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#8]
I just incorporated a new impulse response into the sonification manager.  I got this impulse response from a site that says that the file is CC Public Domain.  I'd like to double check that we can indeed use this recording and that the license entry is correct.  @samreid - since you seem to know the most about licensing, please take a look at tambo/audio/license.json, check out the entry for empty-apartment-bedroom-06.mp3, and let me know if all is good.  There is a link to the location where the sound was obtained in the license file, but in case you need it here, it came from http://www.openairlib.net/auralizationdb/content/empty-apartment-bedroom.

**Comment by jbphet** [comment]
One thing I'm wondering about in particular is the copyright entry.  It doesn't seem quite correct to have it say that CU owns the copyright, but I'm not sure what should go here in its stead.

**Comment by samreid** [comment]
Public domain audio is probably fine, but let's run it past @kathy-phet before publishing something with it.

How about:
```js
  "empty-apartment-bedroom-06.mp3": {
    "text": [
      "An Impulse Response I recorded in the bedroom of an empty apartment close to my house. Recorded with an H4n, source was a handclap. Recorded at 96kHz/24-bit.",
      "Attribute this work to: www.openairlib.net"
    ],
    "projectURL": "http://www.openairlib.net/auralizationdb/content/empty-apartment-bedroom",
    "license": "Public Domain Creative Commons"
  },
```

**Comment by jbphet** [comment]
I went with something close to what @samreid suggested, but a little simpler.  It looks like this:

```
  "empty-apartment-bedroom-06.mp3": {
    "text": [
      "obtained from www.openairlib.net"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "Public Domain Creative Commons",
    "notes": "downloaded from http://www.openairlib.net/auralizationdb/content/empty-apartment-bedroom"
  },
```

**Comment by jbphet** [comment]
Over the @kathy-phet to decide if this is okay.  Also adding @ariel-phet in case he can just resolve.

If licensing issues for impulse responses like this are a hassle, we could obtain a stereo recorder for about $200 or so where we could just record our own.

**Comment by ariel-phet** [comment]
Spoke with @jbphet - if such recording needs come up in the future, or we are unhappy with the current impulse, or we are unhappy with the licensing we will just go ahead and purchase the recording device.

Reassigning to @jbphet to bring up to Kathy at status meeting and get a quick answer.

**Comment by jbphet** [comment]
Okay, sounds like this is settled and we will use the "empty apartment" impulse response, at least for now. Closing.
