### ISSUE TITLE
Add soundManager.containsSoundGenerator

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#80]
From https://github.com/phetsims/wave-interference/issues/436.  We cannot add sound generators in static space, so for some dynamic code (like https://github.com/phetsims/wave-interference/issues/436) we need a way to keep track if which sound generators have been added to the sound manager.  It seems reasonable to add `soundManager.containsSoundGenerator`.  I'll add it and reassign to @jbphet for review and discussion.

**Comment by samreid** [comment]
@jbphet can you please review?

**Comment by jbphet** [comment]
Looks reasonably good, and I agree that it's needed.  One thought: how about `hasSoundGenerator` instead of `containsSoundGenerator`, since that would be more consistent with `Node.hasChild` in scenery and `Property.hasListener` in axon?

**Comment by samreid** [comment]
Good idea, I renamed it.  Ready for re-review.

**Comment by jbphet** [comment]
Looks good, thanks, closing.
