### ISSUE TITLE
Create a bandpass filter option

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#84]
From slack:

@samreid said:
> Ashton and I would like to implement lowpass filter + q filter on looped mp3 clips.  I see that we have support for it in NoiseGenerator, any ideas or plans how we would do this for other sounds outside of NoiseGenerator?

@jbphet replied:
> I don't have any plans at the moment, but this seems like a desire that could come up again, so I think there should be some options to SoundClip that, if set, it would put the specified filter in the path.  Or maybe a subclass, so that the base class doesn't get too complicated.

@samreid said:
> Does web audio provide a Node that would accomplish that?  If not, what is the anticipated implementation strategy?  Would you like to be the one to implement it?

@jbphet said:
> Yes, web audio provides a filter node, see https://developer.mozilla.org/en-US/docs/Web/API/BiquadFilterNode.  My first inclination would be to do something like what is done in NoiseGenerator where the options decide what, if anything (in terms of filters), to put into the signal path.  However, if it seems like it starts to make the options overly complicated, I'd look at doing it in a subclass, i.e. FilteredSoundClip, where it would "unplug" the the sound generator in the base class and insert a filter in the chain.  I'm happy to implement it if you need me too, but I can't get to it right away.  Maybe late tomorrow at the earliest.  I'm also not possessive about it, so if you want to jump in, feel free.  We could have a quick startup talk when you do if it would be helpful.

@samreid said:
> Thanks!  I’ll create an issue and self-assign for now.  Once I take a look around I’ll have a better sense of scope and timing.

@jbphet said:
> Sound like a good plan.
> Around line 72 of NoiseGenerator is where the code starts that decides about the filters.  It allows all three filter types to be added, but I don't think we probably want to do that long term - I think clients should generally only need one.  Given your description, maybe all you want is the bandpass, so you could go with that, at least for now.  There is also an API to allow the center of the band to be changed.

**Comment by samreid** [comment]
I originally attempted this strategy:

```js
    /**
     * Inserts a new Node to take effect immediately after the bufferSource.  Inserts are in reverse order, so that:
     * mySoundClip.insertNode(a)
     * mySoundClip.insertNode(b)
     * would have the effect of soundBuffer => b => a => localGainNode => masterGainNode
     * TODO: can/should we reverse this order?
     * @param {Node} downstreamNode
     * @public
     */
    insertNode( downstreamNode ) {

      // disconnect previous node
      this.bufferSource.disconnect( this.downstreamNode );

      // set up next node
      this.bufferSource.connect( downstreamNode );
      downstreamNode.connect( this.downstreamNode );

      // Ready for next time
      this.downstreamNode = downstreamNode;
    }
```

But unfortunately, the bufferSource is created lazily on play.  Instead, I added an `additionalNodes` argument to the constructor which specifies the nodes on startup.  It seems to be working well in testing, though I only tested with a single additionalNode.  Commit coming shortly.

**Comment by samreid** [comment]
I added `options.additionalNodes` in the above commit, @jbphet can you please review at your convenience?

**Comment by jbphet** [comment]
Here are some initial comments:

+ This API puts a lot of requirements onto the client, such as needing to know the Web Audio API and how to create filters and other nodes that may be needed.  Why not create a subclass of `SoundClip` with filter options and specify filter params there?
+ If we **do** go with this API, the documentation needs to be clear about where these are inserted in the signal chain and whether multiple nodes are expected to be connected to one another already.
+ The code seems to be reconnecting the audio nodes on every `play` call.  This is not necessary.  You should be able to connect the audio nodes together and just keep track of the "connection point" and have the `AudioBufferSourceNode` connect to that once it's created.

Back to @samreid for next steps.

**Comment by samreid** [comment]
> Why not create a subclass of SoundClip with filter options and specify filter params there?

That sounds like we would end up creating and maintaining our own API as an alternative to something that is already standardized, well documented, very flexible and very clear.

> If we do go with this API, the documentation needs to be clear about where these are inserted in the signal chain and whether multiple nodes are expected to be connected to one another already.

The existing documentation says:
```js
// {AudioNode[]} Nodes that will be connected in the specified order, between the bufferSource and localGainNode
additionalNodes: []
```
Is that correct and complete?

> The code seems to be reconnecting the audio nodes on every play call. This is not necessary. You should be able to connect the audio nodes together and just keep track of the "connection point" and have the AudioBufferSourceNode connect to that once it's created.

Good point, I'll commit something shortly.

**Comment by samreid** [comment]
Can you please review the commit, in particular to double-check the `connect` ordering?

**Comment by jbphet** [comment]
Apologies for not getting to this sooner.

I reviewed the code and made some changes to the way the audio nodes are inserted into the signal chain that I think is a bit simpler and, hopefully, more clear. When I went to test the changes, the only usage I found was in `PeakToneGenerator`, which doesn't seem to be used anymore.  So, here are some questions:

+ Do we still need support for additional audio nodes?  I'm not opposed to it, but we should probably add a test harness if so.
+ Do we still need  `PeakToneGenerator`?
+ Assuming we want to keep them, please review my changes.
+ Assuming we keep this, I'm inclined to move it into `SoundGenerator`, since it is basic enough functionality that it could also apply to sound sources like oscillators, noise generators, etc.  Agreed?

**Comment by samreid** [comment]
I removed PeakToneGenerator.  I think one day we will want to leverage the additional audio nodes functionality. I skimmed the changes in https://github.com/phetsims/tambo/commit/49b9691dd0df72a5fde82a6ac4303354ba352c20 and it seemed reasonable, but, like you, I had no way to test it.  Likewise, I don't feel I have time at the moment to develop a test case for this.

@jbphet how do you recommend to proceed?  Some options:
* Delete it for now but leave this issue open for future reference
* Leave the code as it is but untested (and document accordingly)
* See if there is an intern that could work on developing a test case for this

**Comment by jbphet** [comment]
Here's what I'll do:

- [ ] Move the code to support additional audio nodes to `SoundGenerator`
- [ ] Implement a test case that adds a reverb (convolver) node, since there may be a need to this in the Proportions & Ratios sim
- [ ] Make sure this all works and, if so, close the issue

**Comment by jbphet** [comment]
Implemented as described above, test case seems to work well, closing.
