### ISSUE TITLE
TODOs should have issue assigned

### ISSUE THREAD

**Issue by Denz1994** [phetsims/tambo#86]
As part of [issue](https://github.com/phetsims/chipper/issues/815), it was decided that TODOs in common code repos should have an issue assigned to them or be addressed. I am assigning this issue to you to handle all of the TODOs in Tambo:

- [x] ContinuousPropertySoundGenerator (6 TODOs)
- [x] CommonSoundPlayers (1 TODO)
- [x] SoundManager (1 TODO)

**Comment by jbphet** [comment]
All TODO items have been addressed, removed, or linked to an issue.  Closing.
