### ISSUE TITLE
Remove unused sounds, iteration 1

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#87]
There are a lot of experimental common sounds being added to tambo at the moment, and at some point there is going to be a buildup of sounds that were tried out, rejected, and forgotten.  I'm going to create an issue to take a pass through and remove any unused sounds, set it as deferred, and put an event on my calendar for three months from now to remind me to get rid of all the unused sound.  I'll probably have to do this every few month for a while until the sounds are more settled upon.

**Comment by samreid** [comment]
Since it has been 3 months since the original post, I'll remove the deferred label. @jbphet feel free to readjust as appropriate.

**Comment by jbphet** [comment]
I just went through the sounds in tambo looking for unused ones, and only found two.  They didn't seem particularly useful, so I did indeed delete them.  It's possible that I deleted some of the other sounds that were no longer used after we'd experimented with them (I vaguely remember doing this).  At any rate, I think that should do it for this issue.  Closing.
