### ISSUE TITLE
Convert SoundClip.isPlaying to a BooleanProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#88]
For a proposed feature in Wave Interference, I need to know when a SoundClip stops playing.  Therefore it would be useful if `isPlaying` was converted to a `Property` that can be observed.

On slack, I asked:

> Can I change SoundClip.isPlaying to a BooleanProperty so I can get a notification when it stops playing?

@zepumph responded

> Sounds fun to me!

and @chrisklus gave a 👍 

This seems like a general improvement that could be used in other places, so I'm inclined to commit and reassign to @jbphet for review.  I'll keep the `isPlaying` interface for backward compatibility, but @jbphet can comment whether that is desired.

**Comment by samreid** [comment]
Proposed change committed, @jbphet can you please review?

**Comment by jbphet** [comment]
Looks good to me, seems like a reasonable approach.  Closing.
