### ISSUE TITLE
general.soundEnabledProperty should be changed to general.soundManager.soundEnabledProperty

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#89]
From today's meeting.

**Comment by samreid** [comment]
Also pertains to https://github.com/phetsims/joist/issues/591

**Comment by samreid** [comment]
I committed this change, @zepumph do you mind reviewing?  It should be relatively fast.

**Comment by zepumph** [comment]
This felt a bit more reusable (though there isn't a reason for it yet). Does that feel good to you?

**Comment by samreid** [comment]
Yes, that's great, thanks!  Anything else for this issue?
