### ISSUE TITLE
Use Enumeration in ScreenSelectionSoundGenerator

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#92]
In https://github.com/phetsims/wave-interference/issues/471 @emily-phet asked to add the home screen and navigation bar buttons to Waves Intro.  I thought it would be an improvement to use Enumeration values instead of magic numbers.  I also made minor edits to code comments.  @jbphet can you please review at your convenience?  Are you also planning to move `ScreenSelectionSoundGenerator` to joist?

**Comment by jbphet** [comment]
Enum looks good, thanks.  Closing.
