### ISSUE TITLE
Create more subtle slider click sounds

### ISSUE THREAD

**Issue by samreid** [phetsims/tambo#94]
During https://github.com/phetsims/wave-interference/issues/474 @ariel-phet recommended a subtler slider click sound.  @Ashton-Morris can you please schedule a short call with @ariel-phet to discuss it?

We are currently using 

```js
  const sliderDecreaseClickSound = require( 'sound!TAMBO/slider-click-02.mp3' );
  const sliderIncreaseClickSound = require( 'sound!TAMBO/slider-click-01.mp3' );
```

**Comment by ariel-phet** [comment]
Met with @Ashton-Morris, I think he has a clear idea of the direction now.
