### ISSUE TITLE
Improve the stubbed audio context

### ISSUE THREAD

**Issue by jbphet** [phetsims/tambo#99]
There is some duplication in the stubbed audio context.  This can be improved by making stubbed sub-components, such as a stubbed `AudioParam`.

**Comment by jbphet** [comment]
I did a fair amount of updating of the stubbed audio context and then tested using the `forceStubbedAudioContext` query parameter.

@KatieWoe - could you please have the QA team test that this is working on Internet Explorer?  The idea would be to test sims that support sound, such as friction, john-travoltage, gravity-force-lab, ohms-law; and verify that the built versions of these sims run from master without crashing IE.  No sound generation is expected, we just need to make sure that they don't crash.

I don't think it is necessary to test all sims, just four or five.  Please record which ones were tested and what the results were and assign this issue back to me.  If problems are found, please do your best to make sure that they are related to the stubbed audio context before assigning back to me - I don't want to end up fixing or sorting through a bunch of unrelated issues as a result of this testing.

Feel free to contact me on Slack/Zoom to discuss if it would help.

**Comment by KatieWoe** [comment]
Things seem ok. Tested on Arithmetic, Friction, John Travoltage, Ohm's Law, and Waves Intro.

**Comment by jbphet** [comment]
Cool, thanks.  Closing.
